var language = {
	Generic : {
		Announcement : {
			kAnnouncementLengthWarning : 'Длина сообщения не должна превышать 4000 символов, продолжить?',
			kAreYouSureToDelete : 'Помеченные сообщения будут удалены. Вы уверены?',
			kErrPublicOnPortal : 'Публичное объявление обязательно должно быть опубликовано на портале',
			kDescription : 'Сообщение',
			kCheckMessageToDelete : 'Для удаления нужно пометить сообщение',
			kEnterAnnName : 'Введите тему сообщения'
		},
		Assignment : {
			KHomeAssignmentWillBeSave4AllClasses : 'Внимание! Этот вариант КТП используется в {0} группах!\nВы действительно желаете изменить домашнее задание в КТП?',
			kATAssignmentType : 'Тип задания',
			kHomeAssignment : 'Домашнее задание',
			kSureToDeleteAssignment : 'Вы действительно хотите удалить задание?',
			kATChooseType : 'Выбрать тип',
			kSelectingLessonFromKTP : 'Выбор урока из КТП',
			kATTKRTheme : 'Оценка за тему',
			kATPleaseSelectAssignmentType : 'Пожалуйста, выберите тип задания',
			kATHomeWork : 'Домашняя работа',
			kUnableRetrieveHomeWorkText : 'Невозможно получить текст домашнего задания. До этого занятия не проводились уроки из КТП',
			kChangeHomeWorkInKTP : 'При сохранении задания изменить информацию по домашнему заданию в КТП',
			kATAssignmentTheme : 'Тема задания',
			kLessonInKTP : 'Урок в тематическом планировании',
			kATEnterAssignmentTheme : 'Пожалуйста, введите тему задания',
			kATAssignmentThemeNotMayBe : 'Тема задания не должна превышать 200 символов'
		},
		Buttons : {
			kEditAttachment : 'Сменить файл',
			kImportOU : 'Импорт ОО',
			kCancel : 'Отмена',
			kCreate : 'Создать',
			kAttachFile : 'Присоединить файл',
			kSelect : 'Выбрать',
			kBack : 'Вернуться',
			kEdit : 'Редактировать',
			kSend : 'Отправить',
			kSave : 'Сохранить',
			kToUp : 'Наверх',
			kRemove : 'Удалить',
			kContinue : 'Продолжить',
			kApply : 'Применить',
			kReset : 'Восстановить',
			kRecruit : 'Принять',
			kRefresh : 'Обновить',
			kAdd : 'Добавить'
		},
		Calendar : {
			kErrSeats2 : 'В поле Максимальная наполняемость должно быть введено целое число число от 1 до 100',
			kErrorStartDateGTDueDate : 'Дата начала интервала позже по времени, чем дата окончания интервала',
			kBtnCancelLessons : 'Отменить занятия',
			kImportName : 'XML-файл с расписанием',
			kAddLesson : 'Добавить занятие',
			kMsgNotDeleted : 'Никакая информация, связанная с занятиями за выбранный день, не была удалена.',
			kSelectRangeAndWeekPattern : 'Выбрать временной интервал и периодичность занятий',
			kEditLessonExist : 'Уроки пересекаются между собой!',
			kMsgConfirmDelLesson : 'Эта информация будет удалена. Вы уверены?',
			kErrMsgInputDataRangeEnd : 'Определите дату конца интервала',
			kMsgConfirm : 'Сбор статистики может занять несколько минут. Продолжить?',
			kAttendance : 'посещаемость',
			kTimeNoOrdered : 'Время начала уроков не согласовано с порядком их следования',
			kErrWidth : 'В поле Ширина (м) должно быть введено дробное число число от 1 до 100',
			kMsgDeletedSuccess : 'Данные успешно удалены.',
			kFoundInfoIUP : 'По {0} параллели обнаружена следующая информация:',
			kErrMsgInvalidDataRangeStart : 'Некорректная дата начала интервала изменения',
			kErrorRoleCannotBeEmpty : 'Выберите роль пользователей',
			kSelectWeekCntInPattern : 'Укажите периодичность занятий',
			kErrMsgInvalidDataRangeEnd : 'Некорректная дата конца интервала изменения',
			kSetRelay : 'Определите, пожалуйста, смену',
			kStartTimeMust : 'Время начала урока должно быть раньше времени окончания.',
			kErrLen : 'В поле Длина (м) должно быть введено дробное число число от 1 до 100',
			kCrossTime : 'Предупреждение: некоторые уроки пересекаются по времени',
			kAssignments : 'задания',
			kCrossName : 'Предупреждение: уже есть урок с таким номером',
			kAllDaysConfirm : 'Внимание! Вы действительно хотите сделать расписание звонков \nдля всех дней недели таким, как для выбранного дня?',
			kFieldLevelLessonCannotBeEmpty : 'Поле "Смена / урок" не должно быть пустым',
			kLessonNotFound : 'В указанный день нет занятий в расписании',
			kSelected : 'Выбрано',
			kApplySchedule : 'Применить расписание',
			kNoCheckedLessons : 'Нет отмеченных для удаления уроков',
			kErrMsgInputDataRangeStart : 'Определите дату начала интервала',
			kSetLessonNumber : 'Определите, пожалуйста, № урока',
			kArea : 'Площадь',
			kOf : 'из',
			kErrArea : 'В поле Площадь должно быть введено дробное число больше либо равно единице',
			kTitle2 : 'Импорт расписания',
			kFieldCannotBeEmpty : 'Поле не должно быть пустым',
			kGivTime : 'Определите, пожалуйста, время.',
			kErrMsgInputDataRange : 'Введите временной интервал',
			kLinkLesson : 'связанные темы уроков из КТП',
			kLessonWrongDatePeriod : 'Указанная дата находится за пределами учебного года',
			kErrorEndDateGTEndYear : 'Дата окончания интервала позже по времени, чем дата конца учебного года',
			kFieldLessonDayCannotBeEmpty : 'Поле "День занятия" не должно быть пустым',
			kRoomNumber : 'Номер/название',
			kFoundInfoClass : 'По {0} классу обнаружена следующая информация:',
			kErrorStartDateLTStartYear : 'Дата начала интервала раньше по времени, чем дата начала учебного года',
			kFloor : 'Этаж',
			kClose : 'Закрыть',
			kWidth : 'Ширина (м)',
			kSeats : 'Максимальная наполняемость',
			kResults : 'оценки',
			kCrossLessonTime : 'Предупреждение: Урок № {0} пересекается по времени',
			k1st : 'Первая',
			kLen : 'Длина (м)'
		},
		ClassManagement : {
			kMsgMustSelectPreSchoolClassTeachers : 'Необходимо выбрать воспитателей',
			kRoomGroupWarn1 : 'В помещении занимается группа. В одном помещении может быть несколько групп только с режимом кратковременного пребывания (ГКП), для групп с иным режимом выделяется отдельное помещение.',
			kRoomGroupWarn2 : 'В помещении занимается группа с другим режимом пребывания.',
			kSubjectGroupName : 'Название предмето-группы',
			kMsgDOUGroupAgeCategory : 'Пожалуйста, укажите возрастную категорию',
			kMsgClassEducProgram : 'Пожалуйста, укажите программу обучения',
			kEnterNewNameSG : 'Введите новое название предмето-группы',
			kAreYouSureSelectSubjectGroupsStep1 : 'Вы уверены, что хотите объединить выбранные предмето-группы?',
			kAreYouSureSelectSubjectGroupsStep2 : 'Внимание! Убедитесь в правильности выбора предмето-групп. В дальнейшем отмена данных изменений невозможна! Обратное разделение объединенной предмето-группы будет невозможно! Вы желаете продолжить?',
			kUnionSubjectGroups : 'Объединение предмето-групп',
			kMsgStayRegime : 'Пожалуйста, укажите режим пребывания',
			kDOUGroupType : 'Тип группы',
			kLevelName : 'Уровень освоения',
			kMsgDelSubject : 'Предмет будет удален из ',
			kMsgNoSelectedClasses : 'Нет отмеченных для удаления ',
			kCountCheckSubjectGroups : 'Количество выбранных предмето-групп должно быть не менее двух',
			kSubjectName : 'Название предмета',
			kMsgClassProfile : 'Пожалуйста, укажите профиль',
			kMsgDOUGroupType : 'Пожалуйста, укажите тип группы',
			kChooseSubjectGroups : 'Выбрать предмето-группы',
			kDefineAddSchoolEducProgramsW : 'Чтобы добавить объединения, задайте программы обучения.',
			kMsgClassType : 'Пожалуйста, укажите тип класса',
			kCantCopyUnsavedData : 'Данные были изменены и не сохранены. Нельзя копировать несохранённый состав подгрупп!',
			kConfirmCopyStudGroupsToNextPeriods : 'Внимание! Текущий состав выбранных подгрупп для выбранного учебного периода будет скопирован\nво все последующие учебные периоды, для которых не задан состав этих подгрупп.\nВы желаете продолжить?',
			kMsgDOUGroupAge : 'Пожалуйста, укажите возрастной диапазон',
			kUnionOperationSuccess : 'Операция объединения выполнена успешно',
			kErrGroupSave : 'Невозможно сохранить/создать группу без помещения, если не выставлен флажок "Не выгружать сведения о группе в ФСПЭО"',
			kMsgGroupSpecialization : 'Пожалуйста, укажите специализацию группы',
			kConfirmChangeCurrPlanForClass2 : 'Изменение типа учебного плана повлечет за собой преобразование предмето-групп. Обратный переход на \'Классический\' учебный план будет невозможен. Вы желаете продолжить?',
			kMsgCommentsTooLong : 'Поле комментария должно содержать не более 2000 символов',
			kNotAvailableToDelete : 'Невозможно удалить, т.к. используется в документах о движении!',
			kSubjectGroups : 'Предмето-группы',
			kExistSubjectGroupName : 'Предмето-группа с таким именем уже существует. Введите, пожалуйста, другое название.',
			kMerge : 'Объединить',
			kGrade : 'Параллель'
		},
		Common : {
			kOpenInNewWindow : '[откроется в новом окне]',
			kImportFile : 'Файл импорта',
			kErrTrustedAppCodeSurroundSpaces : 'Код доверенного приложения не может начинаться или заканчиваться пробелом',
			kErrNewPassword_ : 'Пароль не может быть пустым',
			kDistrict : 'Район',
			kErrMsgNoChecks : 'Нет отметок для удаления!',
			kUnexpErr : 'Неожиданная ошибка!',
			kErrMoreThanZero : 'Введите целое число больше нуля',
			kErrInvalidEndDate : 'Неверная дата окончания',
			kErrLoginValidSimbols : 'Имя пользователя может содержать только буквы, цифры и символы',
			kSuccessAttachFile : 'Добавление файла выполнено успешно',
			kErrorTrustedAppCodeMustHave : 'Код доверенного приложения должен содержать не менее 6 символов.',
			kShortName : 'Краткое название',
			kErrInvalidStartDate : 'Неверная дата начала',
			kAlertNotCloseWindow : 'Пожалуйста не закрывайте окно импорта!',
			kMaxHeavySessionsReached : 'Извините, в данный момент выполняется максимальное количество ресурсоёмких операций в системе. Пожалуйста, попробуйте повторить это действие через несколько минут',
			kServerErr : 'Ошибка сервера.(http code 500)',
			kConfirmNoSave : 'Данные были изменены. Вернуться без сохранения изменений?',
			kErrorMsgEmotional : 'Ошибка!',
			kAnswerAbsent : 'Введите ответ на контрольный вопрос',
			kErrLogin : 'Имя пользователя не может быть пустым',
			kErrPWDSurroundSpaces : 'Пароль не может начинаться или заканчиваться пробелом',
			kCheckAll : 'Выделить все',
			kSchoolYear : 'Учебный год',
			kErrNewPassword : 'Новый пароль не может быть пустым',
			kQuestionAbsent : 'Введите контрольный вопрос',
			kMustUseFilter : 'Задайте параметры фильтров и нажмите кнопку "Применить", либо воспользуйтесь поиском по фамилии',
			kErrorPasswordMustHave : 'Пароль должен содержать не менее 6 символов.',
			kConfirmPassword : 'Подтвердите новый пароль:',
			kCheckUncheckAll : 'Выделить все/Очистить все',
			kAnswerLengthInvalid : 'Длина ответа не может быть меньше 6 символов!',
			kLinkFile : 'Ссылка на файл',
			kNoDelSubjects : 'Нет отмеченных для удаления предметов',
			kSuccessEditAttachmentDescription : 'Описание файла успешно отредактировано',
			kAttachedFile : 'Присоединенный файл',
			kChangeHistory : 'Журнал изменений',
			kErrMsgExist : 'Такое название уже существует',
			kChoose : 'Выбрать',
			kSetValue : 'Установленное значение',
			kErrAttachFile : 'В момент добавления файла произошла ошибка',
			kChangePassword : 'Сменить пароль',
			kEmploy : 'Используется',
			kProvince : 'Муниципальный район',
			kErrPageAccess : 'Обратитесь к администратору системы, чтобы получить право доступа.',
			kEOType : 'Тип ОО',
			kMsgAreYouSure : 'Вы уверены?',
			kNewPasswordMustNotEqualOld : 'Новый пароль должен отличаться от старого',
			kSimplePassword : 'Вы ввели слишком простой пароль. Пароль не должен совпадать с логином, фамилией, именем, не должен быть простой суммой фамилии и имени',
			kbadFirstLetter : 'Первая буква должна быть в диапазоне от А до Я',
			kLoadError : 'Ошибка загрузки',
			kMaxInput : 'Максимально допустимое значение для ввода - ',
			kDataSaved : 'Данные были успешно сохранены.',
			kValidationError : 'Заполнены не все поля, обязательные для заполнения!',
			kCreateNewPassword : 'Придумайте новый пароль и введите его в этой и в следующей строке',
			kAlertImporting : 'Импорт всех элементов может занять длительное время',
			kEditAttachmentDescription : 'Редактировать описание файла',
			kAlertImporting2 : '(более 5 минут)',
			kErrInvalidDate : 'Неверная дата',
			kStateOn : 'Состояние на',
			kSelectFile : 'Выбрать файл',
			kNewPassword : 'Новый пароль:',
			kStud_FI : 'Фамилия, имя учащегося',
			kSubject : 'Предмет',
			kName : 'Название',
			kLast : 'Последняя',
			kLoad : 'Загрузка',
			kCity : 'Населенный пункт',
			kEdit : 'Редактировать',
			kDate : 'Дата',
			kWait : 'Подождите',
			kSave : 'Сохранить изменения',
			kRemove : 'Удалить',
			kOk : 'Ок',
			kNo : 'Нет',
			kEO : 'Образовательная организация',
			kEnterIntegerFrom1To : 'Введите целое число от 1 до',
			kMinInput : 'Минимально допустимое значение для ввода - ',
			kEnterTheName : 'Введите наименование',
			kErrMissTime : 'Время определено не полностью',
			kSimplePasswordShort : 'Вы ввели слишком простой пароль. Пароль не должен совпадать с логином',
			kSchoolPeriod : 'Учебный период',
			kErrNumericPasswordsRestricted : 'Пароли, состоящие только из цифр, запрещены администратором сервера',
			kStartEndDatesInCurrYear : 'Дата начала и дата конца должны находиться в границах выбранного учебного года',
			kDateMustBeInCurrYear : 'Дата должна находиться в границах выбранного учебного года',
			kCfrmContinue : 'Вы желаете продолжить?',
			kErrDifferentPassword : 'Вы ввели разные пароли!',
			kExportIntoExcel : 'Для сохранения в формате Excel требуется наличие Microsoft Excel или OpenOffice Calc на компьютере пользователя. Продолжить?',
			kDefineTermsTypes : 'Необходимо задать типы периодов для всех параллелей профиля',
			kPasswordIsSaved : 'Пароль успешно сохранен',
			kNoChangesData : 'Нет данных об изменениях',
			kFileName : 'Имя файла',
			kResetChanges : 'Изменения формы сброшены!',
			kDisplayName : 'Имя на экране',
			kChoseControlQuestion : 'Выберите контрольный вопрос',
			kPageErrWrongCall : 'Ошибка страницы: Не верный вызов',
			kDetails : 'Подробности',
			kComment : 'Комментарий',
			kMsgStartBeforeEnd : 'Дата окончания должна быть позже даты начала',
			kNoDetails : 'Нет подробностей',
			kProcessing : 'Обработка',
			kEnterCurrPassword : 'Введите пароль, который вы использовали для текущего входа в систему',
			kUserName : 'Имя пользователя',
			kAttention : 'Внимание!',
			kTimeOutOccured4Ajax : 'Ошибка! Ваш сеанс работы был завершен',
			kCancel_2 : 'Отменить',
			kSetEmailOrMobilephone : 'Необходимо заполнить либо поле "Мобильный телефон", либо поле "E-Mail".',
			kContinue : 'Продолжить?',
			kErrOldPassword : 'Введите старый пароль',
			kErrInvalidDateNotEmpty : 'Неверная дата (дата не должна быть пустой)',
			kMiddleName : 'Отчество',
			kNoAsk : 'больше не спрашивать',
			kField : 'Поле',
			kState : 'Регион',
			kRoles : 'Роли',
			kUnCheckAll : 'Очистить все',
			kMustUseFind : 'Задайте первые буквы фамилии и нажмите кнопку "Найти", либо воспользуйтесь фильтром',
			kAuthorOfChanges : 'Автор изменений',
			kOut : 'выбыл',
			kGr8 : 'смеш. дошкольная',
			kGr3 : 'смеш. ранняя',
			kGr2 : 'первая младшая',
			kGr1 : 'вторая ран.возраста',
			kGr0 : 'первая ран.возраста',
			kGr7 : 'подготовительная',
			kGr6 : 'старшая',
			kGr5 : 'средняя',
			kGr4 : 'вторая младшая',
			kAll : 'Все',
			kAdd : 'Добавить',
			kYes : 'Да',
			kCurrPassword : 'Текущий пароль:'
		},
		Constructor : {
			kButtonImportName : 'Импорт отчетов',
			kAlertConcat : 'Нельзя использовать конкатенацию с другими операциями',
			kErrEmptyReportGroupName : 'Название группы не может быть пустым',
			kAlertNoMove : 'Не выбраны строки для перемещения',
			kMsgTest : 'Будет произведено тестирование отчета.\nЭто может занять несколько минут. Если тестирование\nпройдет успешно, отчет будет опубликован.\nВыполнить публикацию?',
			kAlertNoRBrackets : 'Не хватает закрывающих скобок',
			kAlertSameFieldsInSortOnDel : 'В сортировке не должно оставаться одинаковых полей',
			kConfirmDelete : 'В случае удаления объекта(ов),\nвся зависимая информация будет удалена!\nПродолжить?',
			kConfirmQFields : 'Обнаружены зависимые возвращаемые поля. При удалении\nданного поля, они также будут удалены. Продолжить?',
			kEnterInteger : 'Введите целое число',
			kAlertNoDel : 'Не выбраны строки для удаления',
			kDescrTooLong : 'Слишком длинный комментарий',
			kInvalidMonth : 'Месяц введен с ошибкой',
			kAlertNoObjectsToDel : 'Не выбраны объекты для удаления',
			kEnterReportName : 'Введите название отчета',
			kConfirmDelString : 'Строка будет удалена. Продолжить?',
			kConfirmDelReport : 'Отчет будет удален. Продолжить?',
			kInvalidNumber : 'Число введено с ошибкой',
			kConfirmSortings : 'Обнаружены зависимые сортировки. При удалении\nданного поля, они также будут удалены. Продолжить?',
			kNeed2columns : 'Для сводного отчета необходимо более 2-х полей.',
			kAlertNoLBrackets : 'Не хватает открывающих скобок',
			kConfirmDelFields : 'Выбранные поля будут удалены. Продолжить?',
			kNeedCheckSorts : 'На этапе Сортировка не забудьте отметить первые 2-а поля для сортировки по возрастанию.',
			kNeedMoreReportsForExport : 'Выберите хотя бы один отчет для экспорта!',
			kInvalidDate : 'Дата введена с ошибкой',
			kConfirmChangeSort : 'Обнаружены зависимые сортировки. При изменении\nполей, они будут изменены или удалены. Продолжить?',
			kConfirmChangeQf : 'Обнаружены зависимые возвращаемые поля. При изменении\nполей, они будут изменены или удалены. Продолжить?',
			kCloseWithoutSaving : 'Закрыть без сохранения изменений?',
			kAlertNoFields : 'Не выбраны поля',
			kDeleteMainColumns : 'Будут удалены некоторые из главных полей сводного отчета. Продолжить?',
			kErrFieldNameExists : 'Необходимо задать несовпадающие имена заголовкам столбцов',
			kAlertNoFieldName : 'Введите название столбца',
			kAlertSystemReport : 'Замечание: общесистемные отчеты могут быть доступны только пользователю с ролью "Управление образования"',
			kAlertSameFieldsInSort : 'В сортировке не должно быть одинаковых полей',
			kInvalidDateFormat_UseDDMMYY : 'Неправильный формат даты. Используйте формат дд.мм.гг',
			kAlertInvalidSymbol : 'Использованы запрещенные символы',
			kAlertInvalidConst : 'Константа должна быть числом и не может быть равной 0',
			kAlertSameFieldsInGroup : 'В группировке не должно быть одинаковых полей',
			kConfirmAddFieldS : 'Обнаружены сортировки. Добавить соответствующие поля группировки?',
			kConfirmAddFieldR : 'Обнаружены возвращаемые поля. Добавить соответствующие поля группировки?',
			kAlertUnmeaningExpression : 'Выражение не имеет смысла'
		},
		StatReports : {
			kPresetIndicatorGroup : 'Предустановленный отчет',
			kAddSubIndicatorGroup : 'Добавить вложенную группу показателей',
			kCreateNewGroup : 'Создать новый отчет',
			kIndicatorsWasSaved : 'Показатели успешно сохранены',
			kEducInstitutionsWasLoaded : 'Список образовательных организаций успешно загружен',
			kEnterCorrectDataInRedFields : 'Для сохранения введите корректные данные в поля, выделенные красной рамкой',
			kIndicatorGroupsWasLoaded : 'Группы успешно загружены',
			kEditingExplanation : 'Редактирование пояснения',
			kIndicatorWasSaved : 'Показатель успешно сохранен',
			kIndicatorGroupListIsEmpty : 'Отчеты не найдены',
			kCreatingIndicator : 'Создание показателя',
			kIndicatorsPublishedSuccessfully : 'Отчеты успешно опубликованы',
			kMustSelectIndicatorGroup : 'Необходимо выбрать группу показателей',
			kSelectPredefinedGroup : 'Выбрать предустановленный отчет',
			kNumber : 'Числовой',
			kDataOpenedForEditing : 'Данные для редактирования успешно открыты',
			kCfrmIndicatorCalcExpRemove : 'Связь с вычислителем будет удалена.',
			kErrEditExplanation : 'Ошибка при редактировании пояснения',
			kIndicatorValueType : 'Тип значения показателя',
			kIndicatorsWasLoaded : 'Показатели успешно загружены',
			kIndicatorName : 'Наименование показателя',
			kCfmRemoveReport : 'По данному отчету в БД могут присутствовать заполненные данные. Вы действительно желаете удалить отчет?',
			kPredefinedIndicatorSelected : 'Предустановленный отчет успешно выбран',
			kParentIndicatorGroupName : 'Наименование родительской группы показателей',
			kCfrmChangeIndicatorValueType : 'Вы изменили тип значения показателя. Все заполненные значения будут удалены.',
			kNestedIndicators : 'Вложенные показатели',
			kIndicatorGroupCreating : 'Создание группы показателей отчета',
			kSelectCalculator : 'Выберите вычислитель',
			kNotSelectedIndicatorGroups : 'Не выбрана группа показателей',
			kLogical : 'Логический (да/нет)',
			kEditingIndicator : 'Редактирование показателя',
			kReportName : 'Наименование отчета',
			kEnterOnlyNumbers : 'В данное поле можно вводить только цифры',
			kCalcWasSuccess : 'Авторасчет выполнен успешно',
			kSavingError : 'Во время сохранения изменений произошла ошибка',
			kEnteredIncorrectData : 'Введены некорректные данные',
			kCalculatorListWasLoaded : 'Список вычислителей загружен',
			kIndicatorGroupSuccessApproved : 'Отчет утвержден успешно',
			kCreatingReport : 'Создание отчета',
			kErrIndicatorListLoading : 'Ошибка загрузки списка показателей',
			kEducInst : 'Образовательных организаций',
			kIndicatorAdded : 'Показатель успешно добавлен',
			kEducManagements : 'Управлений образования',
			kAutomaticCalculationErr : 'Во время авторасчета произошла ошибка',
			kEnterParamValue : 'Введите значения параметров',
			kImpossibleMakeChangesAfterApproval : 'После утверждения данные по отчету нельзя будет изменить. Вы желаете продолжить?',
			kIndicatorsDataWasLoaded : 'Данные по показателям успешно загружены',
			kChangesWasSaved : 'Изменения успешно сохранены',
			kSubEmListWasLoaded : 'Список подчиненных УО успешно загружен',
			kRemoveRefWithCalculator : 'Удалить связь с вычислителем',
			kSelectingPredefinedIndicator : 'Выбор предустановленного отчета',
			kStatReportIndicatorGroupLevel : 'Подзаголовок',
			kConfirm : 'Подтверждение',
			kExplanationWasAddedSuccess : 'Пояснение успешно добавлено',
			kStatReportIndicatorGroupTitle : 'Заголовок',
			kAddSubIndicator : 'Добавить вложенный показатель',
			kAttention : 'Внимание',
			kDataWasChangedContinueWithoutChangingData : 'Данные изменены. Вы хотите продолжить работу без изменения данных?',
			kCfmRemoveIndicator : 'По данному показателю или группе показателей отчета в БД могут присутствовать заполненные данные. Вы действительно желаете удалить показатель?',
			kIndicatorsInfoWasLoaded : 'Информация о показателях успешно загружена',
			kPresetIndicatorsIsEmpty : 'Нет предустановленных отчетов',
			kIndicatorListLoading : 'Загрузка списка показателей',
			kValue : 'Значение',
			kIndicatorRemoved : 'Показатель успешно удален',
			kIndicatorGroupListWasLoaded : 'Список групп показателей успешно загружен',
			kIndicatorGroupAdded : 'Группа показателей успешно добавлена',
			kErrApproving : 'Ошибка при утверждении',
			kCalculatorsNotFounded : 'Вычислителей не найдено',
			kChooseCalculator : 'Выбрать вычислитель',
			kIndicatorGroupName : 'Наименование группы показателей'
		},
		SMS : {
			kSmartsApplication : 'Заявление на деактивацию SMS-рассылки',
			kAfterFailureYouCantReceiveSmsResults : 'Вы уверены? После отказа вы не сможете получать SMS с оценками',
			kGetRemainingMoney : 'Да, получить остаток',
			kYourBalance : 'Ваш баланс составляет',
			kNotAllFieldsFilled : 'Не все поля формы заполнены'
		},
		QualityAssessment : {
			kMaxScoreFieldOnlyNumbers : 'В поле "Максимальный балл" можно вводить только цифры',
			kAlertMaxScore : 'Заполните поле "Максимальный балл".\nЗначение должно быть больше нуля.',
			kTestTaskSuccessEdition : 'Задание успешно отредактировано',
			kNotExistsTestPlan : 'Для формирования плана контрольной работы добавьте в план задание по кнопке "Добавить задание" либо выполните импорт готового плана контрольной работы по кнопке "Импорт"',
			kAlertTaskDifficult : 'Выберите уровень сложности',
			kSuccessDeleteTestPlan : 'План контрольной работы успешно удален',
			kAreYouSureDeleteTestTask : 'В случае удаления задания плана контрольной работы также будет удален и результат по этому заданию из протокола контрольной работы. Вы хотите продолжить?',
			kAreYouSureDeleteTestPlan : 'В случае удаления плана контрольной работы также будет удален и протокол контрольной работы. Вы хотите продолжить?',
			kConfirmExistsLessonsOrTestPlansForSubjectGradeSchool : 'Внимание! С данным предметом уже связан кодификатор начальной школы, в случае продолжения все прописанные КЭС в планах уроков или протоколах будут очищены. Вы желаете продолжить?',
			kConfirmExistsLessonsOrTestPlansForSubjectOGE : 'Внимание! С данным предметом уже связан кодификатор ОГЭ, в случае продолжения все прописанные КЭС в планах уроков или протоколах будут очищены. Вы желаете продолжить?',
			kConfirmExistsLessonsOrTestPlansForSubjectEGE : 'Внимание! С данным предметом уже связан кодификатор ЕГЭ, в случае продолжения все прописанные КЭС в планах уроков или протоколах будут очищены. Вы желаете продолжить?',
			kAlertTaskMistakeType : 'Выберите вид ошибки',
			kTestPlanResults : 'Протокол контрольной работы',
			kTestLevelEditionSuccess : 'Уровень контрольной работы успешно изменен',
			kEditTestTask : 'Редактировать задание',
			kAdditional : 'Дополнительно',
			kEditionTask : 'Редактирование задания',
			kSelectedTasksSuccessDeleted : 'Выбранные задания успешно удалены',
			kForImportSelectEmptyTestPlan : 'Импорт возможен только в пустой план контрольной работы.',
			kErrTestPlanSaving : 'Ошибка сохранения плана контрольной работы',
			kAdditionTask : 'Добавление задания',
			kExportTestPlanConfirm : 'Будет произведена выгрузка Плана контрольной работы.',
			kResultsWasSaved : 'Результаты успешно сохранены',
			kTestTaskNotSelected : 'Не выбраны задания для удаления'
		},
		Curriculum : {
			kCurriculumNotFilled : 'Для данного предмета не заполнено календарно-тематическое планирование.',
			kInvalidImportFileCsv : 'Можно импортировать только файлы c расширением csv',
			kErrMsgYouNeedSelectPlanOrUnitFirst : 'Сначала необходимо выбрать предмет или раздел',
			kSubjectNotHaveContentElementsInCurrYear : 'Для данного предмета в текущем учебном году не загружен кодификатор элементов содержания ФИПИ',
			kGroupCurrDelConfirm : 'Удаление раздела повлечет за собой удаление всех ссылок из этого раздела. Продолжить?',
			kErrorStartDateGTDueDate : 'Дата начала позже по времени, чем дата выполнения',
			kErrMsgCantCopyPlan : 'Можно копировать только раздел или урок. Для копирования варианта КТП необходимо воспользоваться экспортом/импортом',
			kErrorStartDateGTDateYear : 'Дата начала задания выходит за пределы \nучебного года.\nПожалуйста, выберите дату между',
			kErrDescriptionTooLong : 'Описание ссылки не может превышать 200 символов',
			kMsgChangeNLessonInUnit : 'Выбранный номер урока в разделе уже занят другим уроком.\nПри сохранении остальные уроки будут смещены. Продолжить?',
			kErrSubjectGroupGradesNotSelected : 'Не выбраны параллели обучения',
			kBookRef : 'Материалы, пособия',
			kErrMsgCantEditPlan : 'Можно редактировать только раздел или урок',
			kEmptyPlanUnits : 'Для выбранного предмета нет плана уроков',
			kCurriculum : 'Календарно-тематическое планирование',
			kElementContent : 'Элемент содержания',
			kErrMsgYouNeedSelectPlanFirst : 'Сначала необходимо выбрать предмет и класс, затем выбрать вид отчёта и выделить в  окне один из вариантов КТП',
			kErrMsgYouNeedSelectUnitOrLessonFirst : 'Сначала необходимо выбрать раздел или урок',
			kErrVariantNameRepeat : 'Название варианта не может повторяться',
			kGoEdit : 'Перейти к редактированию',
			kErrorDueDateGTDateYear : 'Дата выполнения задания выходит за пределы \nучебного года.\nПожалуйста, выберите дату между',
			kAttachFileDescrLimit : 'Описание присоединенного файла не должно превышать 3600 знаков',
			kForExportSelectVariantWithUnit : 'Для экспорта необходимо выбрать конкретный вариант, содержащий хотя бы один раздел',
			kErrorBadDueDate : 'Неверная дата выполнения',
			kExportVariantConfirm : 'Будет произведена выгрузка КТП: \"%\".\nПредупреждение: прикрепленные файлы не экспортируются',
			kInvalidImportFileFormat : 'Можно импортировать только файлы формата Microsoft Excel 2003 c расширением xls',
			kYourAssignmentOnVacations : 'Ваше задание задано на каникулы! Продолжить?',
			kErrMsgCantViewPlan : 'Можно просматривать только раздел или урок',
			kDescription : 'Описание',
			kPleaseWait : 'Пожалуйста, подождите',
			kForImportSelectEmptyVariant : 'Импорт возможен только в пустой КТП. Выберите вариант КТП, не содержащий ни одного раздела. Или создайте новый вариант и произведите импорт в него.',
			kYourAssignmentOnWeekEnd : 'Ваше задание задано на выходной день! Продолжить?',
			kUnit : 'Раздел',
			kEnterFileName : 'Введите имя файла',
			kInvalidImportFile : 'Можно импортировать только файлы c расширением ',
			kNoElementsInAssignment : 'В это задание не было включено ни одного элемента',
			kNoLessonInJournal0 : 'Для этого занятия',
			kNoLessonInJournal2 : 'не назначена тема урока из календарно-тематического планирования',
			kBtnCancel : 'Отмена',
			kAtLeastOneStudentMustBeSelected : 'Должен быть выбран хотя бы один ',
			kMsgDeletingUnit : 'Удаление раздела повлечет удаление всех уроков, входящих в него. Вы уверены?',
			kErrTermsNotSelected : 'Не выбраны периоды обучения',
			kYourAssignmentOnHoliday : 'Ваше задание задано на праздник! Продолжить?',
			kCodeElementContent : 'Код элемента содержания (КЭС)',
			kLessonHomework : 'Домашнее задание',
			kErrMsgCantDeletePlan : 'Можно удалять только раздел или урок',
			kConfirmCopyCurriculum : 'Учебный план будет скопирован из предыдущего учебного периода. Вы желаете продолжить?',
			kImportVariant : 'Импорт варианта КТП',
			kErrLinkCantBeEmpty : 'Поле ссылки не может быть пустым',
			kMsgChangeNUnitInPlan : 'Выбранный номер раздела уже занят другим разделом.\nПри сохранении остальные разделы будут смещены. Продолжить?',
			kTitleLessonView2 : 'Подробности урока',
			kToAll : 'Всем',
			kErrEmptyVariantName : 'Название варианта не может быть пустым',
			kChooseClassMeetingDay : 'Выберите занятие'
		},
		EGE : {
			kSelectStudent : 'Выберите учащегося',
			kUnknownPersons : 'Не связанные учащиеся',
			KAllPersons : 'Все учащиеся'
		},
		EM : {
			kErrorNormNamesTheSame : 'Нельзя определять нормативы с одинаковыми названиями',
			kEnterNormSummFrom_0_To_ : 'Определите сумму норматива, число от 0 до ',
			kUpdatePosConfirm : 'Должностные данные будут обновлены согласно последней аттестации. Продолжить?',
			kNPADetails : 'Реквизиты НПА',
			kDefineNewNorm : 'Задайте все поля для нового норматива',
			kImportEGE : 'Импорт результатов ЕГЭ',
			kErrCantDeleteAllNorms : 'Нельзя удалить все нормативы из таблицы',
			kErrorEmptyRuleResol : 'Поле \'Руководящее постановление\' не может быть пустым',
			kConfirmOnDeleteNormsInfo : 'Вы действительно хотите удалить сведения о нормативах вместе с таблицей?',
			kAddNewNorm : 'Добавить новый норматив',
			kDefineNorm : 'Задайте все поля для норматива',
			kConfirmOnDeleteSelectedNorms : 'Вы действительно хотите удалить выбранные нормативы из таблицы?',
			kSchoolCodeSaved : 'Код ОО успешно сохранён'
		},
		EMReports : {
			kInputLastFirstNamesOrCertificate : 'Для поиска необходимо ввести фамилию и имя ребёнка и/или номер сертификата доп. образования',
			kReportTakesTime : 'Подготовка отчёта займёт некоторое время',
			kChoosePayNorms : 'Выберите нормативы родительской платы'
		},
		FilterUsers : {
			kUsersNumberOfPage : 'Число записей на странице должно быть больше нуля'
		},
		Forum : {
			kAlertLongText : 'Текст сообщения не должен превышать 10 000 знаков',
			kConfirmDelMessages : 'Сообщения будут удалены. Вы уверены?',
			kAlertNoCheckedTopics : 'Не выбраны темы для удаления',
			kAlertNoName : 'Ведите название темы',
			kCfrmSetModers : 'На следующем экране вы сможете назначить модераторов всего форума. Продолжить?',
			kAlertNoCheckedMessages : 'Не выбраны сообщения для удаления',
			kConfirmDelTopics : 'Темы будут удалены со всеми сообщениями в них. Вы уверены?',
			kAlertNoMessage : 'Введите текст сообщения'
		},
		Grade : {
			kErr_PayVal : 'В поле "{0}" введите число от {1} до {2}',
			kChoiceWithoutUsed : 'Прежде чем отметить тип экзамена "По выбору", его надо сначала отметить в графе "Использовать"',
			kAddHomeAssignOnNextClassmeeting : 'Добавить домашнее задание на следующее занятие',
			kErrCantDeleteAssign : 'Невозможно удалить задание',
			kActivityRemoved : '--- Удалён ---',
			kOrMakeFieldEmpty : 'или оставьте поле пустым',
			kTestPlan : 'Протокол контрольной работы',
			kAttendanceColumn : 'Посещаемость',
			kZeroMarkConfirm : 'Вы уверены, что хотите выставить 0 баллов?',
			kInvGrade : 'Оценка должна быть целым числом от ',
			kCheckUncheckAll : 'Отметить/снять отметки для этого задания',
			kAddAssignment : 'Добавить задание',
			kAssignments : 'Задания',
			kCreateAssignmentShort : 'Новое задание',
			kDelAssignmentWithMarks : 'По этому заданию выставлены оценки, либо оно задано как обязательное.\nЭта информация будет удалена вместе с заданием! Вы уверены?',
			kAssignmentAdded : 'Задание успешно добавлено',
			kDelAssignsConfirm : 'Вы хотите удалить помеченные задания?',
			kNextClassmeetingDate : 'Дата следующего занятия',
			kNoAssignSelected : 'Ни одно задание не помечено для удаления',
			kCreateAssignment : 'Добавить новое задание',
			kForFillingTestPlan : 'Для заполнения протокола перейдите на экран ',
			kNoTheme : '---Не указана---',
			kEditAssignment : 'Редактировать задание',
			kPayValS : 'Внес. сумма',
			kSubjectPlanHomeAssignmentText : 'Текст домашнего задания из КТП',
			kInvGrade2 : ' до ',
			kCorrection : 'Коррекция',
			kResetDataWithoutSave : 'Данные были изменены. Вы хотите восстановить значения полей без сохранения данных?',
			kErr_AttendCount_Without_Norm : 'Нельзя определить значение "Посещ." без норматива',
			kErrExistsMarks4ThisAss : 'За это задание есть отметки',
			kNoNextClassmeetings : 'В расписании нет следующих занятий',
			kHomeAssignmentText : 'Текст домашнего задания',
			kErr_AttendCountSumm : 'Суммарное значение в полях "Посещ." не должно превышать количество дней в месяце:',
			kErr_AttendCount : 'В поле "Посещ." введите число от 0 до',
			kConfirmOnChangeCM : 'Сохранить изменения перед переходом к другому занятию?',
			kUse : 'Использовать'
		},
		Import : {
			kToImport : 'Импортировать',
			kBeginImport : 'Начать импорт',
			kSuccessImportSchools : 'Следующие ОО успешно импортированы:',
			kFailImportSchools : 'Следующие ОО не были импортированы:',
			kSchoolsAlreadyCreated : 'Все данные ОО уже существуют в системе, поэтому они не будут созданы.',
			kTitleImportEO : 'Импорт списка ОО',
			kStaffImport : 'Импорт сотрудников'
		},
		LearnApp : {
			kEnterGradingScaleName : 'Введите имя оценочной шкалы',
			kAlertInvalidExt : 'Файл должен иметь расширение mdb',
			kEnterNumber0_100 : 'Введите число от 0 до 100',
			kCommentTooLong : 'Комментарий не должен превышать 2000 символов',
			kImportLearnCourses : 'Импорт учебных курсов',
			kSelectGS : 'Выделите название шкалы',
			kSelectLA : 'Выберите учебный курс',
			kLAsNotSelectedToDelete : 'Не выбраны курсы для удаления',
			kEnterLAName : 'Введите название курса',
			kAlertEnterLAName : 'Выберите название курса',
			kSureToDeleteGS : 'Вы действительно хотите удалить оценочную шкалу',
			kAlertEnterFileName : 'Пожалуйста, выберите сначала файл на диске',
			kSelectGSToDelete : 'Выберите оценочную шкалу для удаления',
			kConfirmMayTakeTime : 'Закачка учебного материала на сервер может занять большое количество времени, если используется доступ в Интернет по модему или суммарный размер учебных материалов и медиа-файлов достаточно велик. Выполнить импорт учебных материалов?',
			kServErrFileTooLarge : 'Невозможно сохранить файл. Размер файла не должен превышать ',
			kCantDeleteDefaultGS : 'Шкалу, используемую по умолчанию, удалить нельзя',
			kMsgLAWasDeleted : 'Учебный курс удалён, невозможно выполнить действие',
			kEnterNumberLessThan : 'Введите число меньше, чем'
		},
		Login : {
			kLoginByECardPossibleViaIEorChrome : 'Вход по электронной карте в настоящее время возможен только через браузеры IE и Chrome',
			kNotSetEmailAdress : 'Не введен E-mail адрес.',
			kFirstYouShouldSelect : 'Сначала нужно выбрать...',
			NotSetSecretQuestion : 'Не задан секретный вопрос и ответ для восстановления пароля. Секретный вопрос и ответ можно установить на странице персональных настроек. Для восстановления пароля обратитесь к администратору школы.',
			kECardIDWasReset : 'Ид. электронной карты сброшен',
			kConfirmDeleteHealthData : 'Вы действительно хотите удалить сведения о здоровье учащихся?',
			kNotSetPhoneNumber : 'Не введен номер телефона!',
			kECardIDWasRead : 'Ид. электронной карты считан',
			kErrorAjaxListLoading : 'Ошибка загрузки списка данных!',
			kWinAuthError : 'Ошибка Windows аутентификации',
			kSelectEM : 'Выберите управление образования...',
			kSelectHierarchyLevel : 'Выберите уровень иерархии...',
			kSelectCity : 'Выберите город/село...',
			kEnterLoginAndPassword : 'Введите имя и пароль.',
			kSelectSchoolType : 'Выберите тип ОО...',
			kSelectProvince : 'Выберите муниципальный район...',
			AnswerCanNotBeEmpty : 'Ответ на вопрос не может быть пустым',
			kEnterPassword : 'Введите пароль',
			YouDontChoseRecoveryMode : 'Вы не выбрали способ восстановления пароля',
			kSelectRegion : 'Выберите регион...',
			kFirstYouShouldSelectSchool : 'Сначала нужно выбрать ОО.',
			kSelectSchool : 'Выберите ОО...',
			kEmptyAjaxAnswer : 'Загруженный список данных пуст!',
			kSelectCountry : 'Выберите страну...'
		},
		Messages : {
			kYourDraftWasSaved : 'Ваш черновик сохранен. Чтобы отправить это сообщение, используйте кнопку "Отправить."',
			kNoMessages : 'Сообщений нет',
			kSuccessDeleteMsgs : 'Сообщения успешно удалены',
			kSuccessMoveMsgs : 'Сообщения успешно перемещены',
			kEmptyTo : 'Поле "Кому" не может быть пустым',
			kNotFoundMobPhoneOrPhoneForSchoolSms : 'Для отправки тестового SMS необходимо ввести номер мобильного телефона и получить номер для школьных SMS',
			kFromWhom : 'От кого',
			kWhom : 'Кому',
			kAddedReportFile : 'Приложенный файл отчёта',
			kYourMessageWasSent : 'Ваше сообщение отправлено',
			kPosted : 'Отправлено',
			kNoMessagesSelectedToDelete : 'Не выбраны сообщения для удаления',
			kErrTooBigRecipientList : 'Список получателей слишком большой',
			kEmptyFields : 'Тема и поле сообщения не могут быть одновременно пустыми',
			kTitleReadMsg : 'Прочитать сообщение',
			kNoMessagesSelectedToMove : 'Не выбраны сообщения для перемещения',
			kSaved : 'Сохранено',
			kMsgPosted : 'Ваше сообщение отправлено',
			kLengthMsg : 'Длина сообщения не должна превышать 65535 символов'
		},
		Movement : {
			kErrEmptyDocNumber : '№ документа не может быть пустым',
			kErrMsgAllMoveDocsThisTypeCreated : 'Все документы этого типа сформированы',
			kErrDocDateAfterLastPeriod : 'После окончания последнего учебного периода невозможны документы о зачислении и переводе',
			kEnrollByTitle_ExtImport : 'Расширенный импорт ',
			kNotSelected : 'Не указано',
			kErrSelectDepartReason : 'Выберите причину выбытия',
			kMsgNoOrderedStudentsInClasses : 'Сначала необходимо зачислить учащихся, зачисленных в классы без приказа. Пройдите в раздел системы "Движение" и создайте приказ о зачислении с подтипом "Все зачисленные" и фильтром "Ученики, зачисленные в этот класс без приказа"',
			kErrDocDateRange1 : 'Дата документа должна быть с ',
			kMoveToNextGrade : 'Внимание!!! Для перевода учащихся НА СЛЕДУЮЩИЙ ГОД нельзя использовать тип документа "перевод из класса в класс". Данный тип документа предназначен ТОЛЬКО для перевода из класса в класс в течение учебного года. Продолжить создание приказа?',
			kMustSelectEnrollSource : 'Необходимо выбрать источник зачисления',
			kConfirmDeleteDoc : 'Вы действительно хотите удалить документ?',
			kCantDeleteDocWithRegionMoving : 'Нельзя удалить документ, содержащий зачисление детей из другого округа',
			kErrMsgYouNeedSelectDocSubType : 'Сначала необходимо выбрать подтип документа',
			kConfirmCreateEmptyDoc : 'Вы создаёте пустой документ! Продолжить?',
			kInputBirthCertificateOrPassport : 'Введите свидетельство о рождении или паспорт или часть документа',
			kMsgImportExtAdd : 'Импорт будет работать в режиме добавления новых пользователей.',
			kAskFutureYearCreate : 'Сейчас начнётся формирование нового учебного года.\n\nМожно будет начать вводить данные следующего года, и в то же время работать в текущем учебном году.\n\nПриступить к формированию следующего года?',
			kQueuedImportProcesses : 'Список процессов импорта в очереди',
			kErrMsgYouNeedSelectDocType : 'Сначала необходимо выбрать тип документа',
			kDocDate : 'Дата документа',
			kEnrollByTitle_Import : 'Импорт ',
			kNotAvailableToMove : 'Не доступен, т.к. используется в летнем движении!',
			kNoStudentsForOut : 'Нет доступных для выбытия учащихся',
			kExistsStudentsWithUnresConditionalMove : 'Есть ученики с до сих пор неразрешённым условным переходом из прошлого года.\nНастоятельно рекомендуется разрешить условный переход.\nТакие ученики не могут участвовать в летнем движении.\nНапример:',
			kErrDocDateOutOfYear : 'Дата документа вне летнего периода',
			kMsgNoActiveQueuedImportProcesses : 'Нет активных процессов импорта учащихся в очереди на обработку'
		},
		MySettings : {
			kEnqueueDate : 'Дата \n постановки в очередь',
			kConfirmAgreeConfirm : 'Подтвердите, что Вы действительно соглашаетесь с условиями договора.',
			kStartProcessingDate : 'Дата \n начала обработки',
			kNumberInQueue : 'Номер в очереди',
			kQueueCurrentStatus : 'Текущий \n статус'
		},
		Photo : {
			kRemovePhotoConfirm : 'Вы действительно хотите удалить фотографию пользователя: ',
			kErrorFileName : 'Введите имя файла',
			kPhotoFile_TooLarge : 'Размер файла не должен превышать ',
			kAttachPhoto : 'Прикрепить фото',
			kPhotoFileName_Ext : 'Файл фотографии должен иметь расширение gif, jpeg, jpg или png',
			kPhotoSize : 'Рекомендуемая высота фотографии - 100 пиксел'
		},
		PoolStudents : {
			kErrNotSelectedReason : 'Необходимо указать причину недоступности!',
			kPoolDepartPlace : 'Место выбытия',
			kConfirmCategoryChange : 'Вы уверены, что хотите изменить категорию доступа?',
			kChildWasRefusedToEnroll : 'Ребёнку отказали в зачислении',
			kInaccessibilityReason : 'Причина недоступности',
			kErrInaccessibilityReason : 'Причина недоступности редактируется только в категории \'Архив\'!'
		},
		ReportNames : {
			kReportUnavailable : 'Этот отчет недоступен'
		},
		Reports : {
			kOn : 'на',
			kCheckNorma : 'Выберите норматив',
			kErrEmptySMSText : 'Текст сообщения не должен быть пустым',
			kFIOstud : 'ФИО',
			kOrderNum : '№ п/п',
			kNameEducInst : 'ОО'
		},
		ResourceGroups : {
			kAreYouSureToDeleteDoc : 'Вы уверены, что хотите удалить этот документ?',
			kSelectDocForDel : 'Выберите документ для удаления',
			kSelectLinkForDel : 'Выберите ссылку для удаления',
			kSelectDocForEdit : 'Выберите документ для редактирования',
			kSelectGroupForDel : 'Выберите раздел для удаления',
			kSelectLinkForEdit : 'Выберите ссылку для редактирования',
			kSelectGroupForEdit : 'Выберите раздел для редактирования',
			kErrEmptyGroupName : 'Название раздела не может быть пустым',
			kAreYouSureToDeleteLink : 'Вы уверены, что хотите удалить эту ссылку?'
		},
		SchoolInfo : {
			kerrOshCalculate : '\'Значение этого поля не может быть больше общего значения\'',
			kIncorrectOkved : 'Поле \'{0}\' заполнено неверно. Форматы возможных значений: XX; XX.X; XX.XX; XX.XX.X; XX.XX.XX, где X – число от 0 до 9.',
			kJuridicalAddress : 'Юридический адрес',
			maxOccupancyOnShift : 'Предельная наполняемость в одну смену',
			kIncorrectFoundingDate : 'Некорректная дата основания ОО',
			kEOForm : 'Вид ОО',
			kEOName : 'Краткое наименование ОО',
			kOGRN : 'ОГРН',
			maxOccupancy : 'Предельная наполняемость',
			kWarnAutoCalc : 'ВНИМАНИЕ! Существующие данные будут пересчитаны заново. Вы хотите произвести автоматический расчет?',
			kINN : 'ИНН'
		},
		SchoolSettings : {
			kMaxMark : 'Максимальная отметка',
			kMinMark : 'Минимальная отметка',
			kInputIntegerInRange : 'Введите целое число из диапазона возможных значений',
			kConChangeMarkRange : 'Изменился диапазон возможных отметок, оценочные шкалы будут изменены.\nТакже изменится отображение оценок в журнале и отчетах. Продолжить?',
			kSchoolIsEnabled : 'ОО будет доступна на экране входа в систему',
			kSchoolIsDisabled : 'ОО будет скрыта на экране входа в систему'
		},
		Secure : {
			kIdleTimeMustNotBeLessThan : 'Время неактивности может быть установлено не менее % минут',
			kEditRightsInLocalAccess : 'Редактирование прав доступа возможно только в режиме защищённого доступа. Текущий режим доступа не является защищённым',
			kAreYouSureToSetByDefault : 'Права доступа будут установлены по умолчанию у выбранного типа пользователя'
		},
		ServAdmin : {
			kErrNameIsEmpty : 'Название не может быть пустым',
			kRangeIsExists : 'Данный диапазон уже был добавлен ранее',
			kErrEOFormMustBeSelected : 'Необходимо выбрать вид ОО',
			kOutMailServerAddressIsEmpty : 'Сервер исходящей почты не задан',
			kMustSelectEO : 'Необходимо выбрать ОО',
			kErrNumberSchoolIsEmpty : 'Номер не может быть пустым',
			kErrEOCreate : 'Невозможно создать ОО! Выберите населенный пункт!',
			kEndDateCanntAfter : 'Конечная дата периода не должна быть позднее по времени, чем ',
			kMoreThanOne : 'Для замены нужно более одного элемента списка',
			kEnterMail : 'Введите e-mail',
			kRangeIntersects : 'Данный диапазон пересекается с предыдущим',
			kErrorDateCannt_29_2 : 'Нельзя использовать дату 29 февраля',
			kErrorFormatIPAddress : 'Неверный формат IP-адреса!',
			kErrEMail : 'Указан неверный e-mail!',
			kConfirmNoSchoolsSelect : 'Не выбрано ни одна ОО. Продолжить?',
			kAreYouSureToDelSchool_DataEnter : 'Для данной образовательной организации введены основные данные. При её удалении она станет недоступной для Управления Образования. Продолжить?',
			kCantReplaceToSelf : 'Нельзя заменить на самого себя',
			kSchoolWasCreated : 'Образовательная организация успешно добавлена',
			kThisCreativeIsUsed : 'Этот тип творческого объединения в данной организации используется, поэтому количество не может быть пустым',
			kErrorBound : 'Граница диапазона не может быть пустой!',
			kMustSelectStaff : 'Необходимо выбрать сотрудников',
			kOrLeaveEmpty : 'или оставьте поле пустым',
			kAssignmentDataCantBeEmpty : 'Полное или сокращенное название типа задания не может быть пустым',
			kServAdminMailIsNotValid : 'E-mail администратора сервера введен в неправильном формате',
			kSMSRegistryConfirm : 'Сейчас произойдёт регистрация мобильных телефонов родителей и параметров сервера для SMS. Продолжить?',
			kExistRelatedSchool : 'Внимание! С этой образовательной организацией связана одна из школ из пункта меню "ОО"! Проследите, чтобы полное название организации соответствовало названию ОО!',
			kUnknownError : 'Неизвестная ошибка',
			kMsgBindSchoolWIthRegion : 'Чтобы привязать ОО к району города:\n\tотмените это действие,\n\tвыберите район,\n\tи нажмите "Добавить".',
			kErrParentCity : 'Населенный пункт не может относиться к самому себе',
			kErrMsgParamName : 'Задайте название значения параметра',
			kErrCityImportedFromKladrEdit : 'Населенный пункт импортирован из КЛАДРа. При его изменении, он станет не доступным для работы с КЛАДРом! \nВы действительно хотите изменить \'Муниципальный район\' для него?',
			kOnlyOne : 'Населённый пункт должен содержать только один район, чтобы он стал муниципальным',
			kSetEMail : 'Необходимо заполнить поле "E-Mail"',
			kDocNumber : 'Номер документа',
			kSetXMLFile : 'Пожалуйста, укажите путь к XML файлу',
			kEditEO : 'Изменить свойства ОО для выбранной организации',
			kForeignLanguageNameCantBeEmpty : 'Название иностранного языка не может быть пустым',
			kErrorPeriodContin : 'Между периодами не должно быть промежутков',
			kServAdminMailIsEmpty : 'E-mail администратора сервера не задан',
			kCityImportedFromKladr : ', т.к. населенный пункт импортирован из КЛАДРа',
			kStartDateCanntBefore : 'Начальная дата периода не должна быть раньше по времени, чем ',
			kAreYouSureToDelSchool2 : 'После удаления восстановить выбранную ОО будет невозможно! Продолжить?',
			kAreYouSureToDelSchool3 : 'Удаление ОО займет длительное время. Начать?',
			kConfirmDeleteElement : 'Выбранный объект будет удален. Продолжить?',
			kConfirmAddTemlates : 'В населенном пункте будут добавлены типовые ОО для движения:\n   детсад, школа-сад, ГОО, ЧОО, Вечерн(С)Ш, спец уч-восп учр., СКОО, НПО, СПО, ОО ВО.\nПри необходимости удалите, добавьте или отредактируйте их',
			kOnlyIfNotProvince : 'Населённый пункт должен быть вне муниципального района',
			kParentEM : 'Вышестоящее управление',
			kSchoolInfoWasChanged : 'Сведения об ОО успешно изменены',
			kMailFromIsEmpty : 'Обратный адрес (e-mail) не задан',
			kMailUserIsEmpty : 'Имя пользователя не задано',
			kIpWereOutOfRange : 'Ваш Ip-адрес не будет входить ни в один из диапазонов',
			kAreYouSureToDelSchool : 'Вы действительно хотите удалить выбранную ОО?',
			kConfirmMakeProvince : 'Внимание! Данный район будет удалён из населённого пункта и станет для него муниципальный районом.\n\tЭто действие нельзя будет отменить',
			kMailFromIsNotValid : 'Обратный адрес (e-mail) введен в неправильном формате',
			kParentSubjectShouldHaveMore : 'В группу предметов следует объединять более одного предмета',
			kErrShortNameIsEmpty : 'Краткое название не может быть пустым',
			kMsgSchoolDistict : 'ОО не будет привязана к району города.',
			kIPAddressCantBeEmpty : 'IP-адрес не может быть пустым',
			kErrEmptyFullEOName : 'Полное название ОО не может быть пустым',
			kCreateEO : 'Добавить новую ОО, отсутствующую в предлагаемом списке',
			kErrorBounds : 'Левая граница диапазона не может быть больше правой!',
			kGlobalSubjectAbbrNameCantBeEmpty : 'Сокращенное название не может быть пустым',
			kAddOU : 'Добавить ОО',
			kReplace : 'Заменить',
			kErrorPeriodOverlapped : 'Периоды не должны пересекаться по времени',
			kCantRenameOrRetype : 'Невозможно изменить название или тип',
			kLoginTime : 'Время входа',
			kConfirmRemoveUserSession : 'Вы уверены, что хотите завершить сессию пользователя?',
			kGlobalSubjectNameCantBeEmpty : 'Название не может быть пустым',
			kSelectSchool : 'Выберите ОО',
			kMailPasswordIsEmpty : 'Пароль не задан'
		},
		SetupSchool : {
			kAreYouSureToDeleteSeniority : 'Вы действительно хотите удалить промежуток стажа?',
			kMsgNoSelectedPrograms : 'Нет отмеченных для удаления программ',
			kErrCommissStartGreaterEndDate : 'Дата выписки из протокола не может быть позже даты окончания решения',
			kErrWeekHoursEmptyButYear_Not : 'Нельзя определить часы в год без указания часов в неделю',
			kSaveUserInfo : 'Сохранение сведений',
			kErrHealthViolation_Complex : 'При выборе более одного вида нарушения неоходимо указать сложный дефект',
			kErrEmptyHealthViolation : 'Необходимо выбрать вид нарушения',
			kErrRelativeLastName : 'Укажите фамилию родственника',
			kErrNoStartDate : 'Отсутствует дата начала!',
			kErrMsgParamName : 'Задайте название значения параметра',
			kSelectProgramDirection : 'Задайте направленность программы',
			kConfirmDeleteCommiss : 'Вы действительно хотите удалить решение комиссии?',
			kErrRelativeFirstName : 'Укажите имя родственника',
			kAidExists : 'Для этого родителя уже существует информация с выбранными значениями даты и типа помощи',
			kSenDateGreaterToday : 'Дата стажа больше сегодняшней даты. Продолжить?',
			kErrEmptyPrivilege : 'Необходимо выбрать вид льготного содержания',
			kErrEmptyEducFormAndProgramm : 'Необходимо выбрать форму или программу обучения',
			kErrEmptyCommissNum : 'Номер решения не может быть пустым',
			kSavingPleaseWait : 'Выполняется сохранение',
			kSelectProgramForReplace : 'Выберите программу, на которую Вы хотите заменить редактируемую программу',
			kReplaceProgram : 'Вы действительно хотите заменить редактируемую программу на выбранную?',
			kErrStartGreaterEndDate : 'Дата начала не может быть больше даты прекращения!',
			kChoiceParam : 'Выбор значений параметра',
			kErrRangeIntersection : 'Промежутки стажа не должны пересекаться!',
			kProgramDirectionIsOld : 'Направленность программы устарела. Продолжить?',
			kCharactersAreNotAllowed2 : 'Символы \' \" не допускаются к вводу',
			kCharactersAreNotAllowed1 : 'Символы \\ \' \" не допускаются к вводу',
			kReplaceTo : 'Заменить на',
			kErrEmptyProgramName : 'Название программы не может быть пустым',
			kErrEmptyProgramAttr : 'Краткое название программы не может быть пустым',
			kErrWeekHoursGraterThanYear : 'Часов в неделю не должно быть больше чем в год',
			kEmptyList : 'Нет значений в списке',
			kNotFoundUsersByFilter : 'По указанному фильтру пользователей не найдено',
			kAMandPMmustDiffer : 'Строки \'am\' и \'pm\' должны различаться',
			kEnterNumberNonNegativeOrEmpty : 'Введите неотрицательное число или оставьте поле пустым',
			kReplace : 'Заменить',
			kDoNotSelectExcludeValues : 'Нельзя выбрать взаимоисключающие значения'
		},
		SetupSchoolCalendar : {
			kEnterVariant : 'Введите наименование варианта!',
			kErrDateOutOfYear : 'Дата переноса вне учебного года',
			kTermTypeNameCantBeEmpty : 'Имя типа учебного периода не может быть пустым',
			kMsgNoSelectedProfiles : 'Выберите профили для удаления!',
			kNonStandartYear : 'Создаваемый год находится за пределами текущего учебного года',
			kEndTimeMustBeLater : 'Время окончания должно быть позже времени начала',
			kPhysicalCultureShort : 'Физкультура',
			kEnterSubjectFieldName : 'Задайте название образовательной области',
			kErrorTermsOverlapped : 'Учебные периоды не должны пересекаться по времени',
			kOverflowLimit : 'Нагрузка по компоненту превышает \'Предельно допустимую нагрузку\'.',
			kCurriculumLimitsNotDefined : 'Не заданы нагрузки по компонентам.',
			kYEndDateCanntBefore : 'Конечная дата учебного периода не должна быть позднее конечной даты учебного года',
			kEnterSubGroupShortName : 'Задайте сокращенное название подгруппы',
			kBasisLimitsNotDefined : 'Не заданы нагрузки по федеральному компоненту',
			kChooseComponentsForDeleting : 'Выберите компоненты для удаления!',
			kYearCantBeEmpty : 'Название года не может быть пустым',
			kStudentsWithReasonStatementExists : 'Нельзя открыть новый год, т.к. в нём будут учащиеся, посещающие организации на основании заявления. Количество: ',
			kForeignLangRecomend : 'Вместо использования предмета "Иностранный язык" рекомендуется добавлять предмет в группу "Иностранные языки". Вы желаете продолжить?',
			kStudentsWithDebtWillTransfer : 'На новый год будут перенесены сведения о должниках. Количество: ',
			kErrPublicEventOnPortal : 'Публичное мероприятие обязательно должно быть опубликовано на портале',
			kErrDescriptionEmpty : 'Описание причины переноса не может быть пустым.',
			kErrMsgEqual : 'Даты переноса не могут совпадать.',
			kLimitMustBe : 'Должны быть заданы предельные нагрузки',
			kConfirmOpenFutureYear : 'После открытия нового года никакие данные старого года поменять будет нельзя! Продолжить?',
			kAddSubjectField : 'Создать новую образовательную область',
			kRemoveGroup : 'Подгруппа из этого предмета будет удалена',
			kCreateNewGlobalSubjectConfirm : 'Если общий предмет создан ошибочно, то будут искажены данные в муниципальных отчетах. Убедитесь, что ваш новый предмет действительно отсутствует в списке общих предметов! (например для "Алгебра для начинающих" - следует выбрать "Алгебра", а не создавать новый общий предмет) \n\nВы желаете продолжить?',
			kDifferentLastTermEnds : 'Для периодов различных типов учебный год будет заканчиваться в разное время. Это может привести к ошибкам в отчетах за летний период.',
			kStartDateCanntAfter : 'Начальная дата учебного периода не должна быть раньше по времени, чем начальная дата учебного года',
			kClConGroupWarning : 'В результате изменения списка предметов в группе возможно\nизменение нагрузки в учебном плане',
			kPhysicalCultureFull : 'Физическая культура',
			kEditSubjectField : 'Редактировать название образовательной области',
			kNecessarySetHours : 'Необходимо задать часы',
			kComponent : 'Компонент',
			kNonStandartHolidays : 'Нестандартное количество выходных!',
			kAltNotSel : 'Выберите группы для удаления',
			kCalendarDescriptionCannot : 'Название мероприятия не может быть пустым.',
			kAddComponentLimit : 'Добавить нагрузку по компоненту (часы в неделю)',
			kCurriculumLimitsAdd : 'Для задания нагрузок нажмите кнопку "Добавить".',
			kConfirmOpenFutureYearOrphanage : 'Сейчас начнётся формирование нового учебного года.\nПосле открытия нового года никакие данные старого года поменять будет нельзя! Продолжить?',
			kTermType_ : 'Тип периода',
			kErrNoLimits : 'Задайте предельные нагрузки для всех параллелей профиля',
			kEnterComponentName : 'Введите имя создаваемого компонента!',
			kEnterLimitFirst : 'Сначала нужно задать \'Предельно допустимую нагрузку\'',
			kEnterSubGroupName : 'Задайте название подгруппы',
			kAllCurriculumLimitsDefined : 'Нагрузки по всем компонентам заданы',
			kEnterSubjectName : 'Задайте название предмета',
			kErrDeleteExistsAssignedSubject : 'Невозможно удалить образовательную область. Найдены связанные предметы в других ОО.',
			kClAltDataNotChg : 'Данные не изменились',
			kConfirmMoveDay : 'Расписание будет целиком перенесено с одного дня на другой. Продолжить?',
			kUndefinedLimit : 'Не задана \'Предельно допустимая нагрузка\' для',
			kSumLimit1 : 'Суммарная нагрузка по компонентам для',
			kClErrNoSubj : 'Выберите предметы',
			kFullName : 'Полное название',
			kSelectGlobalSubjectEx : 'Выберите общий предмет, которому соответствует создаваемый вами предмет.<br />Список общих предметов является общим для всех школ на сервере.<br />В случае, если такого общего предмета нет в списке, вы можете создать новый общий предмет.',
			kAllSubjectsAddedToSubjectPlan : 'Для данного компонента все предметы уже добавлены в учебный план',
			kAlertDeleteAll : 'Невозможно удалить все профили учебного плана',
			kTitleCreateTermType : 'Создать новый тип учебного периода',
			kEnterSubjectShortName : 'Задайте сокращенное название предмета',
			kExcludeSubjectsFromRemovedField : 'Предметы из этой образовательной области не будут включены ни в одну из образовательных областей',
			kConDelWarn : 'В результате удаления групп(ы) предметов возможно\nизменение нагрузки в учебном плане'
		},
		SetupSchoolCurPlan : {
			kEnterNumberGreaterEqual_0p1 : 'Пожалуйста, введите число >= 0.01',
			kConf_PlanGreaterLimit_5 : '\nСохранить учебный план?',
			kConf_PlanGreaterLimit_2 : ' ч) превышает заданную предельную нагрузку (',
			kConf_PlanGreaterLimit_3 : ' ч).\nКомпонент: ',
			kConf_PlanGreaterLimit_1 : 'Фактическая нагрузка (',
			kEnterNumberGreater_0 : 'Пожалуйста, введите число больше 0'
		},
		SetupSchoolPortfolio : {
			kGroupPortDelConfirm : 'Удаление раздела повлечет за собой удаление всех ресурсов из этого раздела. Продолжить?',
			kProjectDelConfirm : 'Удаление проекта повлечет за собой удаление всех разделов, ссылок, документов и ресурсов из этого проекта. Продолжить?',
			kErrEmptyFileName : 'Имя файла документа не может быть пустым',
			kErrorDescriptionTooLong : 'Описание ссылки не может превышать 200 символов',
			kErrorLinkCannotBeEmpty : 'Поле ссылки не может быть пустым',
			kErrEmptyPortfolioName : 'Название портфолио не может быть пустым',
			kErrEmptyDocName : 'Название документа не может быть пустым',
			kWaitPageLoading : 'Подождите пока страница полностью загрузится.'
		},
		SetupSchoolResources : {
			kErrEmptyFileName : 'Имя файла документа не может быть пустым',
			kErrEmptyDocName : 'Название документа не может быть пустым',
			kErrInvalidFileExt : 'Недопустимое расширение файла, возможные расширения:'
		},
		SetupSchoolUI : {
			kDataNotModified : 'Данные не были изменены!',
			kMsgMaxQuickUsers : 'Вы ввели максимально допустимое за один сеанс количество новых пользователей!\nВ целях безопасности Вам рекомендуется сохранить данные',
			kErrorURightCannotBeChecked : 'Пользователь не может совмещать функцию тех.персонала с другими функциями',
			kMothers : 'матери',
			kEnterHouse : 'Заполните поле \'Дом\'',
			kErrZipCodeLength : 'Индекс не должен превышать 10 символов',
			kErrEmpty : 'Введите ',
			kErrorBadPasswordConfirm : 'Пароль неверно подтвержден.',
			kMsgSelectFileName : 'Пожалуйста, выберите сначала файл на диске',
			kErrFirstName : 'имя',
			kDelConfirm : 'Вы действительно хотите удалить адрес?',
			kDuplicateFIOInOtherSchools_1 : 'В других ОО найдены записи с таким ФИО',
			kErrLastName : 'фамилию',
			kErrLoginName : 'имя пользователя',
			kChooseLocation : 'Выберите улицу (квартал)',
			kSetEMail : 'Пожалуйста, укажите корректный адрес e-mail',
			kConfirmDismissStaff : 'ПЕРЕД увольнением рекомендуется скорректировать стаж сотрудника!\nВы действительно хотите уволить сотрудника?',
			kSavingTakesTime : 'Сохранение данных займёт некоторое время',
			kConfirmDeleteStaff : 'Внимание! Кнопка \'Удалить\' используется только для удаления ошибочно введённых сотрудников. Эта кнопка полностью удаляет всю информацию о сотруднике, если с ним не связаны классы или предметы.\nЕсли вам нужно уволить сотрудника, используйте кнопку \'Уволить\'.\n\nПродолжить?',
			kErrBirthdate : 'дату рождения',
			kConfirmDissociateParentInUDOD : 'Внимание! Отсоединение родителя от ребёнка в интерфейсе ОДО повлечёт за собой аналогичное отсоединение этого родителя от этого ребёнка также и во всех других ОО,\nи может привести к полному удалению записи об этом родителе из системы.\nКроме того, в интерфейсе ОДО нет возможности обратно присоеденить родителя к ребёнку.\nВы уверены, что хотите отсоединить родителя от ребёнка?',
			kBirthdayLargeToday : 'Дата не может быть позже сегодняшнего дня',
			kErrorURightCannotBeEmpty : 'Пометьте какую-либо из функций пользователя',
			kPersonDataInLocalAccess : 'Просмотр и редактирование персональных данных возможны только в режиме защищённого доступа. Текущий режим доступа не является защищённым',
			kEnterZipCode : 'Поле \'Индекс\' не заполнено. Продолжить?',
			kMsgExample : 'например',
			kChangeZipCode : 'Изменение индекса пользователя приведет к изменению индексов у всех пользователей, проживающих в этом доме. Продолжить?',
			kMobileLenMustBe : 'Длина поля \'{0}\' должна быть равна {1} символам',
			kInvalidFormatSnils : 'Значение в поле \'СНИЛС\' должно быть задано в формате \'123-456-789 12\'',
			kSavingContinue : 'Сохранение данных уже происходит',
			kAttribParamDateLargeToday : ' позже сегодняшнего дня. Продолжить?',
			kResetECardID : 'Пожалуйста, уберите идентификатор электронной карты или измените тип аутентификации',
			kDuplicateFIO_2 : 'Если хотите продолжить сохранение, нажмите \'Продолжить\', если не хотите сохранять изменения, нажмите \'Отмена\'.',
			kDuplicateFIO_1 : 'Запись с таким ФИО уже существует',
			kMsgInpuDelimiter : 'Пожалуйста, укажите символ-разделитель',
			kFieldPhoneHasOnlyNumbers : 'В поле \'{0}\' должны быть указаны только цифры',
			kDeleteUsersInfo : 'Удалить всех отмеченных пользователей?',
			kStrExpireWarning : 'Ваше время неактивности на сервере истекает через 2 минуты.\nНастоятельно рекомендуем Вам сохранить данные в течение этого времени,\nиначе данные могут быть потеряны.',
			kErrInvalidGroupObligatory : 'При задании остальных параметров из группы параметров \'Инвалидность\' обязательно должна быть указана \'Группа инвалидности\'',
			kConfirm : 'Подтверждение',
			kErrMsgDBFilePath : 'Укажите путь к базе данных АРМ "Всеобуч"',
			kConfirmOnQuikSave : 'Вы хотите сохранить изменения?',
			kYouDidNotEnterUserInfo : 'Вы не ввели информацию о пользователе\nЗаполните поля для ввода и нажмите \'Добавить/Сохранить\' для добавления информации\nИли нажмите \'Вернуться\' для отмены ввода данных.',
			kSetECardID : 'Пожалуйста, укажите идентификатор электронной карты',
			kMsgImportExtUpdate : 'Импорт будет работать в режиме обновления уже существующих пользователей. Вы хотите продолжить?',
			kMobileLenMustBeNotEmpty : 'Значение поля \'{0}\' не должно быть пустым',
			kErrorLoginNameAlreadyExists : 'Такое \'Имя пользователя\' уже введено в список!',
			kSetSerialNumberEToken : 'Пожалуйста, укажите серийный номер ключа eToken',
			kFathers : 'отца',
			kConfirmRecruitStaff : 'После приёма сотрудника рекомендуется скорректировать его стаж!\nВы действительно хотите принять сотрудника?'
		},
		Wizard : {
			kSaveOrResetData : 'Данные были изменены. Нажмите \'Сохранить\' или \'Восстановить\''
		}
	}
}
