"""Reverse-engineer the NetSchool (main4) MS SQL schema.

Inputs:
  01_orm_schema.sql            - DDL generated by NHibernate from the application's mappings (authoritative)
  01_orm_schema.entities.tsv   - entity/property -> table/column map
  il_sql.tsv                   - SQL literals joined per .NET method (assembly, type::method, sql)
  Web/**/*.asp|asa|inc         - classic ASP pages with inline SQL
Outputs (into OUT dir):
  02_legacy_tables.sql         - CREATE TABLE for tables only used by raw SQL (inferred)
  03_orm_tables_extra_columns.sql - ALTER TABLE ADD for columns used by raw SQL but not mapped
  04_views_functions_procs.sql - stubs for views / functions / procedures referenced by code
  schema_inventory.json        - machine-readable inventory with evidence
"""
import os, re, sys, json
from collections import defaultdict, Counter

ROOT, SCAN, OUT = sys.argv[1], sys.argv[2], sys.argv[3]

# ---------------------------------------------------------------- ORM schema
TSQL_RESERVED = set('''ADD ALL ALTER AND ANY AS ASC AUTHORIZATION BACKUP BEGIN BETWEEN BREAK BROWSE BULK BY CASCADE CASE CHECK
CHECKPOINT CLOSE CLUSTERED COALESCE COLLATE COLUMN COMMIT COMPUTE CONSTRAINT CONTAINS CONTAINSTABLE CONTINUE CONVERT CREATE
CROSS CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE DBCC DEALLOCATE DECLARE DEFAULT DELETE
DENY DESC DISK DISTINCT DISTRIBUTED DOUBLE DROP DUMP ELSE END ERRLVL ESCAPE EXCEPT EXEC EXECUTE EXISTS EXIT EXTERNAL FETCH FILE
FILLFACTOR FOR FOREIGN FREETEXT FREETEXTTABLE FROM FULL FUNCTION GOTO GRANT GROUP HAVING HOLDLOCK IDENTITY IDENTITY_INSERT
IDENTITYCOL IF IN INDEX INNER INSERT INTERSECT INTO IS JOIN KEY KILL LEFT LIKE LINENO LOAD MERGE NATIONAL NOCHECK NONCLUSTERED
NOT NULL NULLIF OF OFF OFFSETS ON OPEN OPENDATASOURCE OPENQUERY OPENROWSET OPENXML OPTION OR ORDER OUTER OVER PERCENT PIVOT PLAN
PRECISION PRIMARY PRINT PROC PROCEDURE PUBLIC RAISERROR READ READTEXT RECONFIGURE REFERENCES REPLICATION RESTORE RESTRICT RETURN
REVERT REVOKE RIGHT ROLLBACK ROWCOUNT ROWGUIDCOL RULE SAVE SCHEMA SECURITYAUDIT SELECT SEMANTICKEYPHRASETABLE SESSION_USER SET
SETUSER SHUTDOWN SOME STATISTICS SYSTEM_USER TABLE TABLESAMPLE TEXTSIZE THEN TO TOP TRAN TRANSACTION TRIGGER TRUNCATE TRY_CONVERT
TSEQUAL UNION UNIQUE UNPIVOT UPDATE UPDATETEXT USE USER VALUES VARYING VIEW WAITFOR WHEN WHERE WHILE WITH WITHIN WRITETEXT'''.split())

def split_top(s):
    parts, depth, cur = [], 0, ''
    for ch in s:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            parts.append(cur.strip()); cur = ''
        else:
            cur += ch
    if cur.strip():
        parts.append(cur.strip())
    return parts

orm_raw = open(os.path.join(OUT, '01_orm_schema.sql'), encoding='utf-8-sig').read()
orm_tables = {}   # TABLE -> {COL: type}
orm_pk = {}
pretty = []
if not orm_raw.startswith('/*'):
    seen_tables = set()
    for stmt in [x.strip() for x in orm_raw.split('\nGO') if x.strip()]:
        m = re.match(r'create table (\w+) \((.*)\)$', stmt, re.S | re.I)
        if m and m.group(1).upper() in seen_tables:
            pretty.append(f'-- NOTE: {m.group(1)} is mapped twice (case differs, same table on a CI collation); duplicate skipped:\n-- ' + stmt + '\n')
            continue
        if m:
            seen_tables.add(m.group(1).upper())
            items = split_top(m.group(2))
            pkm = [x for x in items if re.match(r'primary key', x, re.I)]
            pk_cols = {c.strip().upper() for c in re.search(r'\((.*)\)', pkm[0]).group(1).split(',')} if pkm else set()
            fixed = []
            for it in items:
                # mapping bug: .Check("PK_X") used as if it were a constraint name -> invalid CHECK
                it = re.sub(r'\s*check\(\s*\w+\s*\)$', '', it, flags=re.I)
                cm = re.match(r'(\w+)(\s+.*)$', it, re.S)
                if cm and not re.match(r'(primary|unique|constraint|foreign|check)\b', it, re.I):
                    col, rest = cm.group(1), cm.group(2)
                    if col.upper() in pk_cols:
                        rest = re.sub(r'\bnull$', 'not null', rest) if not re.search(r'not null$', rest, re.I) else rest
                    if col.upper() in TSQL_RESERVED:
                        col = f'[{col}]'
                    it = col + rest
                elif re.match(r'(primary key|unique)\s*\(', it, re.I):
                    head, cols_ = it.split('(', 1)
                    it = head + '(' + re.sub(r'\b(\w+)\b', lambda mm: f'[{mm.group(1)}]' if mm.group(1).upper() in TSQL_RESERVED else mm.group(1), cols_)
                fixed.append(it)
            items = fixed
            pretty.append(f'CREATE TABLE dbo.{m.group(1)} (\n    ' + ',\n    '.join(items) + '\n);\nGO\n')
        else:
            pretty.append(stmt + ';\nGO\n')
    header = ('/* ============================================================================\n'
              '   01_orm_schema.sql\n'
              '   Generated by NHibernate SchemaExport from the application\'s own FluentNHibernate\n'
              '   mappings (NetCity.NHibernate.Mapping.dll + integration modules). Types, lengths,\n'
              '   nullability, PK, FK and unique constraints are exactly as the ORM expects them.\n'
              '   FK constraint names are NHibernate hashes, not the original names.\n'
              '   ============================================================================ */\n\n')
    orm_raw = header + '\n'.join(pretty)
    open(os.path.join(OUT, '01_orm_schema.sql'), 'w', encoding='utf-8-sig').write(orm_raw)
orm_sql = orm_raw
for m in re.finditer(r'CREATE TABLE dbo\.(\w+) \(\n(.*?)\n\);', orm_sql, re.S):
    cols = {}
    for item in split_top(m.group(2).replace('\n', ' ')):
        pk = re.match(r'primary key \((.*)\)', item, re.I)
        if pk:
            orm_pk[m.group(1).upper()] = [x.strip().upper() for x in pk.group(1).split(',')]
            continue
        cm = re.match(r'\[?(\w+)\]?\s+([A-Za-z0-9]+(?:\([\w, ]+\))?)', item)
        if cm and cm.group(1).lower() not in ('unique', 'constraint', 'foreign', 'check'):
            cols[cm.group(1).upper()] = cm.group(2).upper()
    orm_tables[m.group(1).upper()] = cols

entities = set()
for line in open(os.path.join(OUT, '01_orm_schema.entities.tsv'), encoding='utf-8-sig').read().splitlines()[1:]:
    p = line.split('\t')
    entities.add(p[0].split('.')[-1].upper())
    entities.add(p[1].split('.')[-1].upper())

# global column-type knowledge from ORM (most common type per column name)
col_types = defaultdict(Counter)
for t, cols in orm_tables.items():
    for c, ty in cols.items():
        col_types[c][ty.replace(' IDENTITY', '')] += 1

# ---------------------------------------------------------------- SQL corpus
corpus = []   # (source, sql)
for line in open(os.path.join(SCAN, 'il_sql.tsv'), encoding='utf-8'):
    parts = line.rstrip('\n').split('\t', 2)
    if len(parts) == 3:
        corpus.append((parts[0] + ' ' + parts[1], parts[2]))

def read_text(p):
    raw = open(p, 'rb').read()
    for enc in ('utf-8', 'cp1251'):
        try:
            return raw.decode(enc)
        except UnicodeDecodeError:
            pass
    return raw.decode('latin-1')

lit_re = re.compile(r'"((?:[^"\n]|"")*)"')
for dp, _, fns in os.walk(os.path.join(ROOT, 'Web')):
    for fn in fns:
        if not fn.lower().endswith(('.asp', '.asa', '.inc')):
            continue
        p = os.path.join(dp, fn)
        rel = os.path.relpath(p, ROOT)
        buf = []
        for line in read_text(p).splitlines() + ['']:
            lits = lit_re.findall(line)
            code = line.strip()
            if lits and not code.startswith("'"):
                buf.extend(l.replace('""', '"') for l in lits)
            elif buf:
                corpus.append((rel, ' '.join(buf)))
                buf = []

# ---------------------------------------------------------------- lexical helpers
KW = set('''select from where and or not null is in on as join inner left right outer full cross group order by having
union all distinct top case when then else end set values into update delete insert exists between like with nolock
table view procedure proc function begin declare return returns if while cast convert isnull coalesce count sum max min
avg asc desc output inserted deleted apply pivot unpivot over partition row_number rank dense_rank lateral using matched
merge by option recompile holdlock updlock rowlock readpast tablock try catch go exec execute dual first skip rows
fetch next only offset open close cursor for each primary key default identity nvarchar varchar int bit datetime date
float decimal numeric money char nchar text ntext image uniqueidentifier bigint smallint tinyint'''.split())
IDENT = r'(?:\[?dbo\]?\s*\.\s*)?(\[?[A-Za-z_][A-Za-z0-9_$]*\]?)'

def norm(n):
    return n.strip().strip('[]"').strip().upper()

def strip_sql(s):
    s = re.sub(r"'(?:[^'\n]|''){0,120}'", "''", s)  # short string literals only (stray apostrophes in messages)
    # no "--" comment stripping: corpus lines are joined literals without newlines, it would eat the rest
    s = re.sub(r'/\*.*?\*/', ' ', s, flags=re.S)
    return s

tbl_re = re.compile(r'\b(from|join|into|update|delete\s+from|delete|merge\s+into|merge|truncate\s+table|apply)\s+' + IDENT + r'(\s*\()?', re.I)
alias_re = re.compile(r'\b(?:from|join|update|into|apply)\s+' + IDENT + r'(?:\s*\([^()]*\))?(?:\s+(?:as\s+)?([A-Za-z_][A-Za-z0-9_]*))?', re.I)
comma_tbl_re = re.compile(r',\s*' + IDENT + r'\s+(?:as\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*(?=,|\bwhere\b|\bjoin\b|$)', re.I)
cte_re = re.compile(r'(?:\bwith|,)\s*([A-Za-z_]\w*)\s*(?:\([^()]*\))?\s+as\s*\(', re.I)
exec_re = re.compile(r'\bexec(?:ute)?\s+(?:@\w+\s*=\s*)?' + IDENT, re.I)
dbo_func_re = re.compile(r'\bdbo\s*\.\s*\[?([A-Za-z_]\w*)\]?\s*\(', re.I)
ins_re = re.compile(r'\binsert\s+(?:into\s+)?' + IDENT + r'\s*\(([^()]{1,4000})\)', re.I)
upd_re = re.compile(r'\bupdate\s+' + IDENT + r'\s+set\s+(.*?)(?=\bwhere\b|\bfrom\b|;|$)', re.I | re.S)
qual_re = re.compile(r'\b([A-Za-z_]\w*)\s*\.\s*\[?([A-Za-z_]\w*)\]?(?!\s*\()')
declare_tv_re = re.compile(r'\bdeclare\s+@\w+\s+table\b', re.I)
select_into_re = re.compile(r'\binto\s+#?\w+\s+from\b', re.I)

tables = defaultdict(set)         # TABLE -> sources
tvf = defaultdict(set)            # table-valued functions: FROM X(...)
scalar_funcs = defaultdict(set)   # dbo.X(...)
procs = defaultdict(set)
columns = defaultdict(lambda: defaultdict(set))  # TABLE -> COL -> sources
insert_first = defaultdict(Counter)  # TABLE -> first insert col counts (PK hints)
seq_cols = defaultdict(set)       # TABLE -> columns filled from GEN_ID / sequence (PK hints)

BUILTIN_TVF = {'OPENJSON', 'OPENXML', 'STRING_SPLIT', 'OPENQUERY', 'OPENROWSET', 'CHANGETABLE', 'FREETEXTTABLE', 'CONTAINSTABLE', 'VALUES'}
SYS = re.compile(r'^(SYS|INFORMATION_SCHEMA|MSDB|MASTER|TEMPDB|RDB\$|MON\$|DUAL$|SYSOBJECTS|SYSCOLUMNS)', re.I)

def is_hql(src, raw_name):
    n = raw_name.strip('[]')
    return (n.upper() not in orm_tables and n.upper() in entities and re.search(r'[a-z]', n) and re.search(r'[A-Z]', n))

written = defaultdict(set)        # TABLE -> {insert, update, delete}

for src, sql in corpus:
    s = strip_sql(sql)
    ctes = {norm(m.group(1)) for m in cte_re.finditer(s)}
    stmt_tables = set()
    placeholder_aliases = []
    # aliases introduced in FROM/JOIN (used to detect "UPDATE alias SET ... FROM table alias")
    from_aliases = {m.group(2).lower() for m in re.finditer(r'\b(?:from|join)\s+' + IDENT + r'\s+(?:as\s+)?([A-Za-z_]\w*)', s, re.I)}
    for m in tbl_re.finditer(s):
        kw, raw, paren = m.group(1).lower(), m.group(2), m.group(3)
        n = norm(raw)
        if m.start(2) > 0 and s[m.start(2) - 1] in '#@':
            continue
        if kw in ('update', 'delete') and n.lower() in from_aliases:
            continue
        # "join {0} TOT on ..." -> table name injected at runtime, what remains is only the alias
        gap = s[m.end(1):m.start(2)]
        if (kw in ('from', 'join') and (len(n) <= 4 or len(gap) >= 3) and n not in orm_tables and not paren
                and re.match(r'\s+(on|where|inner|left|join|order|group)\b|\s*(,|\)|$)', s[m.end(2):], re.I)):
            placeholder_aliases.append((m.start(), n.lower()))
            continue
        if n.lower() in KW or raw.startswith(('@', '#')) or n in ctes or len(n) < 3 or SYS.match(n) or '$' in n:
            continue
        if kw.startswith(('into', 'update', 'delete', 'merge', 'truncate')):
            written[n].add(kw.split()[0])
        if re.fullmatch(r'P\d+|\{\d+\}', n):
            continue
        if is_hql(src, raw):
            continue
        if paren and kw in ('from', 'join', 'apply'):
            if n not in BUILTIN_TVF:
                tvf[n].add(src)
            continue
        if paren and kw in ('into',):   # INSERT INTO X (cols) handled as table
            pass
        tables[n].add(src)
        stmt_tables.add(n)
    # alias definitions with positions; a qualified reference resolves to the NEAREST definition,
    # because one method often holds several statements reusing the same alias letters
    alias_defs = defaultdict(list)   # alias -> [(pos, table)]
    for m in alias_re.finditer(s):
        n = norm(m.group(1))
        if n in stmt_tables or n in orm_tables:
            alias_defs[n.lower()].append((m.start(), n))
            a = m.group(2)
            if a and a.lower() not in KW:
                alias_defs[a.lower()].append((m.start(), n))
    for m in comma_tbl_re.finditer(s):
        n = norm(m.group(1))
        if n in stmt_tables or n in orm_tables:
            alias_defs[m.group(2).lower()].append((m.start(), n))
    # derived tables / CTE aliases shadow real tables: ") X" or "X as ("
    for m in re.finditer(r'\)\s*(?:as\s+)?([A-Za-z_]\w*)\b', s, re.I):
        if m.group(1).lower() not in KW:
            alias_defs[m.group(1).lower()].append((m.start(), None))
    for c in ctes:
        for m in re.finditer(r'\b' + re.escape(c) + r'\b', s, re.I):
            alias_defs[c.lower()].append((m.start(), None))
    for pos, a in placeholder_aliases:
        alias_defs[a].append((pos, None))
    for d in alias_defs.values():
        d.sort(key=lambda x: x[0])
    aliases = {a: d[-1][1] for a, d in alias_defs.items()}

    def resolve(a, pos):
        d = alias_defs.get(a)
        if not d:
            return None
        before = [x for x in d if x[0] <= pos]
        best = max(before, key=lambda x: x[0]) if before else min(d, key=lambda x: x[0])
        return best[1]

    for m in exec_re.finditer(s):
        raw = m.group(1).strip('[]')
        n = norm(raw)
        if (n.lower() not in KW and not n.startswith('SP_') and not raw.startswith('@') and len(n) > 3
                and not re.fullmatch(r'\{\d+\}', n) and (raw.isupper() or '_' in raw)):
            procs[n].add(src)
    for m in dbo_func_re.finditer(s):
        scalar_funcs[norm(m.group(1))].add(src)
    for m in ins_re.finditer(s):
        n = norm(m.group(1))
        if n not in tables and n not in orm_tables:
            continue
        cols = [norm(c) for c in m.group(2).split(',')]
        if all(re.fullmatch(r'[A-Z_][A-Z0-9_]*', c) and c.lower() not in KW for c in cols):
            for c in cols:
                columns[n][c].add(src + ' [write]')
            insert_first[n][cols[0]] += 1
            vm = re.search(r'\)\s*values\s*\((.*)', s[m.end():m.end() + 2000], re.I | re.S)
            if vm and re.match(r'\s*gen_id\s*\(|\s*next\s+value\s+for', vm.group(1), re.I):
                seq_cols[n].add(cols[0])
    for m in upd_re.finditer(s):
        n = norm(m.group(1))
        if n.lower() in from_aliases:
            n = resolve(n.lower(), m.end()) or n
        if n not in tables and n not in orm_tables:
            continue
        for c in re.findall(r'(?:^|,)\s*(?:[A-Za-z_]\w*\.)?\[?([A-Za-z_]\w*)\]?\s*=', m.group(2)):
            if c.lower() not in KW and not c.startswith('@'):
                columns[n][norm(c)].add(src + ' [write]')
    for m in qual_re.finditer(s):
        a, c = m.group(1).lower(), norm(m.group(2))
        if m.start() > 0 and s[m.start() - 1] in '@#:.':
            continue
        if a in alias_defs and c.lower() not in KW and a != 'dbo' and not re.fullmatch(r'\d+', c):
            t = resolve(a, m.start())
            if t:
                columns[t][c].add(src)
    # single-table statements: bare identifiers in WHERE / SELECT list / ORDER BY are columns of that table
    real = {t for t in stmt_tables if t in orm_tables or t in tables}
    if len(real) == 1 and not re.search(r'\bjoin\b|\bunion\b|\(\s*select\b|,\s*[A-Za-z_]\w*\s+[A-Za-z_]\w*\s*(?:where|$)', s, re.I):
        t = next(iter(real))
        body = re.sub(r'@\w+|:\w+|\{\d+\}|\b\d+\b', ' ', s)
        sel = re.search(r'\bselect\s+(?:distinct\s+)?(?:top\s*\(?\s*\d+\s*\)?\s+)?(.*?)\bfrom\b', body, re.I | re.S)
        parts = []
        if sel and '*' not in sel.group(1):
            parts.append(sel.group(1))
        w = re.search(r'\bwhere\b(.*?)(?:\border\s+by\b(.*))?$', body, re.I | re.S)
        if w:
            parts.append(w.group(1))
            if w.group(2):
                parts.append(w.group(2))
        for part in parts:
            for idm in re.finditer(r'(?<![\w.@#$])([A-Za-z_][A-Za-z0-9_]*)\b(?!\s*[\(.])', part):
                c = idm.group(1)
                if c.lower() in KW or c.upper() == t or len(c) < 2 or c.lower() in aliases:
                    continue
                # skip "AS alias"
                pre = part[max(0, idm.start() - 4):idm.start()].lower()
                if re.search(r'\bas\s*$', pre):
                    continue
                columns[t][norm(c)].add(src + ' [unqualified]')

# ---------------------------------------------------------------- column cleanup
all_known_cols = set(col_types)
for t, cols in list(columns.items()):
    names = set(cols)
    ref = names | all_known_cols | set(orm_tables.get(t, {}))
    for c in list(cols):
        strong = [x for x in cols[c] if '[unqualified]' not in x]
        # literal split in the middle of an identifier ("...PERIODTYPEI" + "D") -> drop the truncated stub
        if c not in all_known_cols and c not in orm_tables.get(t, {}) and any(o != c and o.startswith(c) and len(o) - len(c) <= 2 for o in ref):
            del cols[c]; continue
        # very short unknown names are almost always aliases of sub-queries, not columns
        if len(c) <= 3 and c not in all_known_cols and c not in orm_tables.get(t, {}) and not any(
                '[write]' in x for x in strong):
            del cols[c]; continue
        if re.fullmatch(r'P\d+|ITEM\d*|ID\d+', c) and c not in orm_tables.get(t, {}):
            del cols[c]; continue

# ---------------------------------------------------------------- classify objects
EXTERNAL_DB = [
    ('LA (la4.gdb, Firebird: learning content / tests)', re.compile(r'LaDAO|LaAccessDAO|\\Learn\\|Lacc\.Processor', re.I)),
    ('KLADR (address classifier DB)', re.compile(r'Kladr', re.I)),
    ('SKUD / turnstile access-control DB', re.compile(r'StudentsInOut', re.I)),
]

def external_db(srcs):
    for name, rx in EXTERNAL_DB:
        if srcs and all(rx.search(x) for x in srcs):
            return name
    return None

def looks_like_view(n):
    return (n.endswith('_V') or n.startswith('V_') or n.endswith('_VIEW') or n.startswith('VW_')
            or (n not in written and re.search(r'^GET_|_TREE$|^TOTALS_AND_|_ON_DATE$', n)))

known = set(orm_tables)
legacy = {}
for n, srcs in tables.items():
    if n in known or n in tvf or n in procs:
        continue
    cols = columns.get(n, {})
    strong = {c for c, ss in cols.items() if any('[unqualified]' not in x for x in ss)}
    # require evidence: referenced from >=2 methods/pages or has strongly-attributed columns
    if len(srcs) < 2 and not strong:
        continue
    # ASP pages glue request-parameter names next to SQL keywords ("delete" + "delClass"); need columns there
    if not cols and all(x.lower().endswith(('.asp', '.inc', '.asa')) for x in srcs):
        continue
    if not re.fullmatch(r'[A-Z][A-Z0-9_]*', n):
        continue
    legacy[n] = srcs

external = defaultdict(dict)
for n, srcs in list(legacy.items()):
    db = external_db(srcs)
    if db:
        external[db][n] = legacy.pop(n)
views = {n: s for n, s in legacy.items() if looks_like_view(n)}
for n in views:
    legacy.pop(n)
for n in ('UNNEST',):
    tvf.pop(n, None)
for n in list(tvf):
    db = external_db(tvf[n])
    if db:
        external[db][n + '()'] = tvf.pop(n)

# ---------------------------------------------------------------- type inference
def infer_type(col):
    if col in col_types:
        return col_types[col].most_common(1)[0][0]
    c = col
    rules = [
        (r'(^|_)(ID|IDS)$|ID$', 'INT'),
        (r'(DATE|_DT|DT$|TIME$|STAMP$|^DT_|MODIFIED|CREATED$)', 'DATETIME'),
        (r'^(IS|HAS|CAN|ALLOW|USE|SHOW|ENABLE)|(FLAG|ENABLED|DISABLED|DELETED|ACTIVE|VISIBLE|LOCKED|ARCHIVE)$', 'BIT'),
        (r'(COUNT|NUM|ORDER|NUMBER|TYPE|KIND|STATUS|LEVEL|YEAR|STATE|MODE|POS|INDEX|IDX|QTY|HOURS|DAY|WEEK|MONTH|RESULT|SCORE|MARK)$', 'INT'),
        (r'(SUM|PRICE|COST|AMOUNT|WEIGHT|RATE|PERCENT|BALANCE|DEBT)$', 'DECIMAL(19,5)'),
        (r'(DATA|BODY|FILE|BLOB|CONTENT|ATTACHMENT|IMAGE|PHOTO|XML|JSON)$', 'VARBINARY(MAX)' if re.search(r'(BLOB|FILE|ATTACHMENT|IMAGE|PHOTO)$', c) else 'NVARCHAR(MAX)'),
        (r'(GUID|UID)$', 'UNIQUEIDENTIFIER'),
    ]
    for pat, ty in rules:
        if re.search(pat, c):
            return ty
    return 'NVARCHAR(255)'

def pk_guess(t, cols):
    if t in seq_cols and seq_cols[t]:
        return next(iter(seq_cols[t]))
    stem_candidates = [t[:-1] + 'ID', t[:-2] + 'ID', t[:-3] + 'YID', t + 'ID', 'ID']
    for c in stem_candidates:
        if c in cols:
            return c
    # ALLOWEDIPRANGES -> RANGEID, ACTIVITYGROUPS -> GROUPID
    singular = re.sub(r'(IES)$', 'Y', t)
    singular = re.sub(r'(ES|S)$', '', singular) if singular == t else singular
    hits = [c for c in cols if c.endswith('ID') and len(c) > 4 and (singular.endswith(c[:-2]) or t.endswith(c[:-2]))]
    if len(hits) == 1:
        return hits[0]
    return None

pk_of = {}   # column name -> table that owns it as PK
for t, pk in orm_pk.items():
    if len(pk) == 1 and pk[0] != 'ID':
        pk_of.setdefault(pk[0], t)

legacy_cols = {}
for t in legacy:
    legacy_cols[t] = dict(sorted(columns.get(t, {}).items()))
for t in sorted(legacy):
    pk = pk_guess(t, legacy_cols[t])
    if pk and pk != 'ID':
        pk_of.setdefault(pk, t)

def src_short(ss, k=3):
    ss = sorted({x.replace(' [unqualified]', '').replace(' [write]', '') for x in ss})
    return '; '.join(ss[:k]) + (f' (+{len(ss) - k})' if len(ss) > k else '')

# ---------------------------------------------------------------- write 02 legacy tables
L = []
L.append('/* ============================================================================\n'
         '   02_legacy_tables.sql\n'
         '   Tables NOT covered by NHibernate mappings, reconstructed from raw SQL found in\n'
         '   NS_DataAccess.dll, NS_DAComWrapper.dll, NetCity.DataAccess.dll, ASP pages, etc.\n'
         '   Column list = union of all columns seen in INSERT / UPDATE / SELECT for the table.\n'
         '   Types are INFERRED (same-named ORM column type, otherwise naming heuristics).\n'
         '   Nullability is unknown -> everything except the guessed PK is NULL.\n'
         '   Confidence per column: [+] seen with explicit alias/insert/update, [?] unqualified only.\n'
         '   ============================================================================ */\n')
fk_lines = []
for t in sorted(legacy):
    cols = legacy_cols[t]
    pk = pk_guess(t, cols)
    L.append(f'-- used by: {src_short(legacy[t])}')
    if t not in written:
        L.append('-- NOTE: only READ by the code (never inserted/updated) -> may actually be a VIEW')
    if not cols:
        L.append(f'-- WARNING: no columns could be inferred for {t}')
    L.append(f'CREATE TABLE dbo.{t} (')
    rows = []
    for c, ss in cols.items():
        conf = '[+]' if any('[unqualified]' not in x for x in ss) else '[?]'
        ty = infer_type(c)
        if c == pk:
            ident = ' IDENTITY(1,1)' if (ty == 'INT' and t in seq_cols) else ''
            rows.append(f'    {c:<32} {ty}{ident} NOT NULL,  -- {conf} PK (guessed)')
        else:
            rows.append(f'    {c:<32} {ty} NULL,  -- {conf}')
        ref = pk_of.get(c)
        if ref and ref != t and c != pk:
            fk_lines.append(f'-- ALTER TABLE dbo.{t} ADD CONSTRAINT FK_{t}_{c} FOREIGN KEY ({c}) REFERENCES dbo.{ref}({c});')
    if pk:
        rows.append(f'    CONSTRAINT PK_{t} PRIMARY KEY ({pk})')
    elif rows:
        rows[-1] = rows[-1].replace(',  --', '   --', 1)
    else:
        rows.append('    DUMMY_ INT NULL  -- placeholder')
    # fix trailing comma on the last column line when a PK constraint follows
    L.extend(rows)
    L.append(');\nGO\n')
L.append('\n/* ---- Probable foreign keys (by column-name convention; review before enabling) ---- */')
L.extend(fk_lines)
open(os.path.join(OUT, '02_legacy_tables.sql'), 'w', encoding='utf-8-sig').write('\n'.join(L) + '\n')

# ---------------------------------------------------------------- write 03 extra columns for ORM tables
E = ['/* ============================================================================\n'
     '   03_orm_tables_extra_columns.sql\n'
     '   Columns referenced by raw SQL on ORM-mapped tables but absent from the mappings\n'
     '   (legacy columns the ORM does not know about). Only alias-qualified / INSERT / UPDATE\n'
     '   evidence is used here, to avoid false positives. Types are inferred.\n'
     '   ============================================================================ */\n']
extra = {}
for t in sorted(orm_tables):
    miss = {}
    for c, ss in columns.get(t, {}).items():
        strong = [x for x in ss if '[unqualified]' not in x]
        distinct = {x.replace(' [write]', '') for x in strong}
        if c not in orm_tables[t] and strong and not re.fullmatch(r'P\d+', c) and (
                len(distinct) >= 2 or any('[write]' in x for x in strong)):
            miss[c] = strong
    if miss:
        extra[t] = miss
        E.append(f'-- {t}')
        for c, ss in sorted(miss.items()):
            E.append(f'ALTER TABLE dbo.{t} ADD {c} {infer_type(c)} NULL;  -- {src_short(ss, 2)}')
        E.append('GO\n')
open(os.path.join(OUT, '03_orm_tables_extra_columns.sql'), 'w', encoding='utf-8-sig').write('\n'.join(E) + '\n')

# ---------------------------------------------------------------- write 04 views / functions / procedures
V = ['/* ============================================================================\n'
     '   04_views_functions_procs.sql\n'
     '   Programmable objects referenced by the application. Their BODIES ARE NOT IN THE\n'
     '   CODE (they lived only in the database), so these are compilable STUBS with the\n'
     '   column list / usage the application expects. They must be re-implemented.\n'
     '   ============================================================================ */\n']
for n in sorted(views):
    cols = dict(sorted(columns.get(n, {}).items()))
    V.append(f'-- VIEW, used by: {src_short(views[n])}')
    sel = ',\n'.join(f'    CAST(NULL AS {infer_type(c)}) AS {c}' for c in cols) or '    CAST(NULL AS INT) AS ID'
    V.append(f'CREATE VIEW dbo.{n} AS\nSELECT\n{sel}\nWHERE 1 = 0;\nGO\n')
for n in sorted(tvf):
    if n in orm_tables or n in legacy:
        continue
    cols = dict(sorted(columns.get(n, {}).items()))
    V.append(f'-- TABLE-VALUED FUNCTION, used by: {src_short(tvf[n])}')
    ex = next(iter(tvf[n]))
    body = ',\n'.join(f'        {c} {infer_type(c)}' for c in cols) or '        ID INT'
    V.append(f'-- TODO: parameters unknown; see call sites\nCREATE FUNCTION dbo.{n} (/* params */)\nRETURNS @r TABLE (\n{body}\n)\nAS\nBEGIN\n    RETURN;\nEND;\nGO\n')
for n in sorted(scalar_funcs):
    if n in tvf:
        continue
    V.append(f'-- SCALAR FUNCTION dbo.{n}, used by: {src_short(scalar_funcs[n])}\n'
             f'-- CREATE FUNCTION dbo.{n} (/* params */) RETURNS INT AS BEGIN RETURN NULL; END;\n')
for n in sorted(procs):
    if n in orm_tables:
        continue
    V.append(f'-- STORED PROCEDURE dbo.{n}, used by: {src_short(procs[n])}\n'
             f'-- CREATE PROCEDURE dbo.{n} AS BEGIN SET NOCOUNT ON; /* TODO */ END;\n')
open(os.path.join(OUT, '04_views_functions_procs.sql'), 'w', encoding='utf-8-sig').write('\n'.join(V) + '\n')

# ---------------------------------------------------------------- write 05 external databases
X = ['/* ============================================================================\n'
     '   05_external_databases.sql\n'
     '   Objects used ONLY by code that talks to OTHER databases (not main4).\n'
     '   Kept for completeness; do not create them in main4.\n'
     '   ============================================================================ */\n']
for db, objs in sorted(external.items()):
    X.append(f'\n/* ---------------- {db} ---------------- */\n')
    for n in sorted(objs):
        base = n.rstrip('()')
        cols = dict(sorted(columns.get(base, {}).items()))
        X.append(f'-- used by: {src_short(objs[n])}')
        if n.endswith('()'):
            X.append(f'-- table-valued function / selectable procedure {base}(...)\n')
            continue
        body = ',\n'.join(f'    {c:<32} {infer_type(c)} NULL' for c in cols) or '    ID INT NULL'
        X.append(f'CREATE TABLE {base} (\n{body}\n);\n')
open(os.path.join(OUT, '05_external_databases.sql'), 'w', encoding='utf-8-sig').write('\n'.join(X) + '\n')

# ---------------------------------------------------------------- inventory
inv = {
    'orm_tables': {t: {'columns': cols, 'raw_sql_users': src_short(tables.get(t, set()), 5)} for t, cols in sorted(orm_tables.items())},
    'legacy_tables': {t: {'columns': {c: {'type': infer_type(c), 'evidence': src_short(ss, 3)} for c, ss in legacy_cols[t].items()},
                          'pk_guess': pk_guess(t, legacy_cols[t]), 'used_by': sorted(legacy[t])[:20]} for t in sorted(legacy)},
    'orm_extra_columns': {t: {c: src_short(ss, 3) for c, ss in m.items()} for t, m in extra.items()},
    'views': {n: sorted(s)[:10] for n, s in sorted(views.items())},
    'table_valued_functions': {n: sorted(s)[:10] for n, s in sorted(tvf.items()) if n not in orm_tables and n not in legacy},
    'scalar_functions': {n: sorted(s)[:10] for n, s in sorted(scalar_funcs.items())},
    'procedures': {n: sorted(s)[:10] for n, s in sorted(procs.items()) if n not in orm_tables},
    'external_databases': {db: {n: sorted(s)[:10] for n, s in sorted(objs.items())} for db, objs in external.items()},
    'rejected_low_evidence_names': sorted(n for n in tables if n not in orm_tables and n not in legacy and n not in views
                                          and n not in tvf and not any(n in o for o in external.values())),
}
json.dump(inv, open(os.path.join(OUT, 'schema_inventory.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)

print('corpus statements:', len(corpus))
print('ORM tables:', len(orm_tables), '| legacy tables:', len(legacy), '| ORM tables w/ extra cols:', len(extra),
      '(', sum(len(v) for v in extra.values()), 'cols )')
print('views:', len(views), '| TVFs:', len(inv['table_valued_functions']), '| scalar funcs:', len(scalar_funcs), '| procs:', len(inv['procedures']))
print('rejected names:', len(inv['rejected_low_evidence_names']))
