<% ' © 2007-2008 IRTech. All rights reserved.

Const kRNStudentsCount = "Количественный состав учащихся"
Const kRNDoublingStudents = "Список учащихся-""дублей"" (образовательные учреждения)"
Const kRNDoublingStudentsPool = "Список учащихся-""дублей"" (выпускники и выбывшие)"
Const kRNMovement = "Движение учащихся общеобразовательных учреждений"
Const kRNCoverageAddEducation = "Охват дополнительным образованием в УДОД"
Const kRNListClassCompleteSet = "Перечень класс – комплектов ОУ, зачисленных в объединение УДОД"
Const kRNTitleListEM = "Суммарный титульный лист комплектования"
Const kRNTotalTitleList = "Сводный титульный лист комплектования"
Const kRNSummaryForm3 = "Сводная Форма №3"
'Const kRNInvalidsInfo = "Информация о детях-инвалидах, обучающихся в МОУ"
Const kRNAddSchoolStudentListOnAssertion = "Список воспитанников, посещающих УДОД по заявлению"
Const kRNEmploymentOfStudentsInGroupsUDOD = "Занятость обучающихся в объединениях МОУДОД"
Const kRNCountComposByYears = "Количественный состав обучающихся по годам обучения МОУ ДОД"
Const kRNAgeComposition = "Возрастной состав обучающихся МОУ ДОД"
Const kRNAddStudentsStudyLoad = "Учебная нагрузка обучающихся в МОУ ДОД"
Const kRNASStudyLoadPerson = "Учебная нагрузка обучающихся в МОУ ДОД (персональный список)"
Const kRNAddSchoolStudentsIntersect = "Пересечение между МОУ ДОД по обучающимся"
Const kRNEmploymentStudentsOUInTheAssociationsUDOD = "Занятость учащихся ОУ в объединениях УДОД"
Const kRNChildrenNotAttendingDOU = "Дети, не посещающие ДОУ"
Const kRNTotalStudentsCntInfo = "Информация о численности детей в ОУ"
Const kRNPMPKRecommendationEM = "Информация о детях, имеющих рекомендации ПМПК на обучение"
%>
