/* ============================================================================
   07_seed_reference.sql
   Reference data the application needs before anything can be created in the UI.
   Roles, rights, functionality types and EO forms are generated from the enums in NetCity.Common.
   Server administrator: /asp/administration/salogin.asp, password: servadmin
   ============================================================================ */
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRAN;

-- DB version checked by COMDataAccess.CheckVersion: STR = MMmm, REV = revision
DELETE FROM dbo.VERSN;
INSERT INTO dbo.VERSN (STR, PRODUCT, ID, REV) VALUES ('0514', 'NS', 1, 65351);

-- FUNCTIONALITYTYPES <- enum FuncType
DELETE FROM dbo.FUNCTIONALITYTYPES;
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (-1, N'Общая');
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (0, N'Орган управления образованием');
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (1, N'Дошкольная образовательная организация');
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (2, N'Общеобразовательная организация');
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (3, N'Организация дополнительного образования');
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (4, N'Профессиональная образовательная организация');
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (5, N'Детский дом');
INSERT INTO dbo.FUNCTIONALITYTYPES (FUNCTIONALITYTYPEID, NAME) VALUES (6, N'Образовательная организация высшего образования');

-- EO_TYPES <- enum EoType (MOV_EOS -> EO_FORMS -> EO_TYPES); replaced only while no organization exists
IF NOT EXISTS (SELECT 1 FROM dbo.MOV_EOS)
BEGIN
    DELETE FROM dbo.EO_FORMS; DELETE FROM dbo.EO_TYPES; DELETE FROM dbo.EO_LEGALFORMS; DELETE FROM dbo.EO_LEGALFORMS_83;
END;
SET IDENTITY_INSERT dbo.EO_TYPES ON;
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 1) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (1, 1, N'Дошкольные образовательные учреждения');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 2) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (2, 2, N'Образовательные учреждения для детей дошкольного и младшего школьного возраста');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 3) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (3, 3, N'Образовательные учреждения дополнительного образования детей');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 4) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (4, 4, N'Межшкольные учебные комбинаты');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 5) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (5, 5, N'Общеобразовательные учреждения');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 6) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (6, 6, N'Общеобразовательные школы-интернаты');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 7) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (7, 7, N'Кадетские школы и кадетские школы-интернаты');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 8) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (8, 8, N'Вечерние (сменные) общеобразовательные учреждения');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 9) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (9, 9, N'Образовательные учреждения для детей, нуждающихся в психолого-педагогической и медико-социальной помощи');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 10) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (10, 10, N'Специальные учебно-воспитательные учреждения для детей и подростков с девиантным поведением');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 11) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (11, 11, N'Специальные (коррекционные) образовательные учреждения');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 12) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (12, 12, N'Образовательные учреждения для детей-сирот и детей, оставшихся без попечения родителей');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 13) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (13, 13, N'Оздоровительные образовательные учреждения санаторного типа');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 14) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (14, 14, N'Суворовские военные, нахимовские военно-морские училища и кадетские корпуса');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 15) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (15, 15, N'Образовательные учреждения начального профессионального образования');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 16) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (16, 16, N'Образовательные учреждения среднего профессионального образования');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 17) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (17, 17, N'Образовательные учреждения высшего профессионального образования');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 18) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (18, 18, N'Военные образовательные учреждения высшего профессионального образования');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_TYPES WHERE EOTYPEID = 19) INSERT INTO dbo.EO_TYPES (EOTYPEID, CLASSIFIERCODE, NAME) VALUES (19, 19, N'Образовательные учреждения дополнительного профессионального образования');
SET IDENTITY_INSERT dbo.EO_TYPES OFF;

-- EO_LEGALFORMS <- enum EoLegalForm; EO_LEGALFORMS_83 = institution type under 83-FZ
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS WHERE EOLEGALFORMID = 1) INSERT INTO dbo.EO_LEGALFORMS (EOLEGALFORMID, NAME) VALUES (1, N'Государственная');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS WHERE EOLEGALFORMID = 2) INSERT INTO dbo.EO_LEGALFORMS (EOLEGALFORMID, NAME) VALUES (2, N'Муниципальная (район)');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS WHERE EOLEGALFORMID = 3) INSERT INTO dbo.EO_LEGALFORMS (EOLEGALFORMID, NAME) VALUES (3, N'Муниципальная (городской округ)');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS WHERE EOLEGALFORMID = 4) INSERT INTO dbo.EO_LEGALFORMS (EOLEGALFORMID, NAME) VALUES (4, N'Негосударственная (частная)');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS WHERE EOLEGALFORMID = 5) INSERT INTO dbo.EO_LEGALFORMS (EOLEGALFORMID, NAME) VALUES (5, N'Индивидуальный предприниматель');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS_83 WHERE EOLEGALFORM83ID = 1) INSERT INTO dbo.EO_LEGALFORMS_83 (EOLEGALFORM83ID, NAME) VALUES (1, N'Бюджетное');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS_83 WHERE EOLEGALFORM83ID = 2) INSERT INTO dbo.EO_LEGALFORMS_83 (EOLEGALFORM83ID, NAME) VALUES (2, N'Казённое');
IF NOT EXISTS (SELECT 1 FROM dbo.EO_LEGALFORMS_83 WHERE EOLEGALFORM83ID = 3) INSERT INTO dbo.EO_LEGALFORMS_83 (EOLEGALFORM83ID, NAME) VALUES (3, N'Автономное');

-- EO_FORMS <- enum EoForm: member '<Type><n>' belongs to EoType '<Type>' (School3 = 20 = default of createArea.asp)
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 1) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (1, '1.1', N'Детский сад', 1, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 2) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (2, '1.2', N'Детский сад общеразвивающего вида', 1, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 3) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (3, '1.3', N'Детский сад компенсирующего вида', 1, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 4) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (4, '1.4', N'Детский сад присмотра и оздоровления', 1, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 5) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (5, '1.5', N'Детский сад комбинированного вида', 1, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 6) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (6, '1.6', N'Центр развития ребенка - детский сад', 1, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 7) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (7, '2.1', N'Начальная школа - детский сад', 2, 2, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 8) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (8, '2.2', N'Прогимназия', 2, 2, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 9) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (9, '2.3', N'Начальная школа - детский сад компенсирующего вида', 2, 2, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 10) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (10, '3.1', N'Дворец (дом) детского творчества', 3, 3, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 11) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (11, '3.2', N'Центр дополнительного образования детей', 3, 3, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 12) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (12, '3.3', N'Станция юных техников (натуралистов, туристов)', 3, 3, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 13) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (13, '3.4', N'Детско-юношеская спортивная школа', 3, 3, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 14) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (14, '3.5', N'Детская школа искусств', 3, 3, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 15) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (15, '3.6', N'Детско-юношеский центр', 3, 3, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 16) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (16, '3.7', N'Детский (подростковый) клуб', 3, 3, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 17) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (17, '4.1', N'Межшкольный учебный комбинат', 3, 3, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 18) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (18, '5.1', N'Начальная общеобразовательная школа', 2, 2, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 19) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (19, '5.2', N'Основная общеобразовательная школа', 2, 2, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 20) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (20, '5.3', N'Средняя общеобразовательная школа', 2, 2, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 21) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (21, '5.4', N'Средняя общеобразовательная школа с углубленным изучением отдельных предметов', 2, 2, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 22) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (22, '5.5', N'Гимназия', 2, 2, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 23) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (23, '5.6', N'Лицей', 2, 2, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 24) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (24, '6.1', N'Школа-интернат начального общего образования', 2, 2, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 25) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (25, '6.2', N'Школа-интернат основного общего образования', 2, 2, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 26) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (26, '6.3', N'Школа-интернат среднего (полного) общего образования', 2, 2, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 27) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (27, '6.4', N'Школа-интернат с углубленным изучением отдельных предметов', 2, 2, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 28) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (28, '7.1', N'Кадетская школа', 2, 2, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 29) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (29, '7.2', N'Кадетская школа-интернат', 2, 2, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 30) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (30, '8.1', N'Вечерняя (сменная) общеобразовательная школа', 2, 2, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 31) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (31, '8.2', N'Открытая (сменная) общеобразовательная школа', 2, 2, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 32) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (32, '8.3', N'Центр образования', 2, 2, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 33) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (33, '8.4', N'Общеобразовательная школа при исправительно-трудовом учреждении', 2, 2, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 34) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (34, '9.1', N'Центр диагностики и консультирования', 3, 3, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 35) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (35, '9.2', N'Центр психолого-медико-социального сопровождения', 3, 3, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 36) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (36, '9.3', N'Центр психолого-педагогической реабилитации и коррекции', 3, 3, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 37) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (37, '9.4', N'Центр социально-трудовой адаптации и профориентации', 3, 3, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 38) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (38, '9.5', N'Центр лечебной педагогики и дифференцированного обучения', 3, 3, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 39) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (39, '10.1', N'Специальная общеобразовательная школа', 2, 2, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 40) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (40, '10.2', N'Специальное профессиональное училище', 2, 2, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 41) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (41, '10.3', N'Специальная (коррекционная) общеобразовательная школа для детей с девиантным поведением', 2, 2, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 42) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (42, '10.4', N'Специальное (коррекционное) профессиональное училище', 2, 2, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 43) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (43, '11.1', N'Специальная (коррекционная) общеобразовательная школа', 2, 2, 11);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 44) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (44, '11.2', N'Специальная (коррекционная) общеобразовательная школа-интернат', 2, 2, 11);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 45) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (45, '11.3', N'Специальный (коррекционный) класс', 2, 2, 11);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 46) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (46, '12.1', N'Детский дом', 5, 5, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 47) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (47, '12.2', N'Детский дом-школа', 5, 5, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 48) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (48, '12.3', N'Школа-интернат для детей-сирот и детей, оставшихся без попечения родителей', 5, 5, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 49) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (49, '12.4', N'Специальный (коррекционный) детский дом', 5, 5, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 50) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (50, '12.5', N'Специальная (коррекционная) школа-интернат для детей-сирот', 5, 5, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 51) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (51, '13.1', N'Санаторная школа-интернат', 2, 2, 13);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 52) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (52, '13.2', N'Санаторно-лесная школа', 2, 2, 13);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 53) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (53, '13.3', N'Санаторный детский дом', 2, 2, 13);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 54) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (54, '14.1', N'Суворовское военное училище', 2, 2, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 55) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (55, '14.2', N'Нахимовское военно-морское училище', 2, 2, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 56) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (56, '14.3', N'Кадетский (морской кадетский) корпус', 2, 2, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 57) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (57, '14.4', N'Военно-музыкальное училище', 2, 2, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 58) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (58, '14.5', N'Казачий кадетский корпус', 2, 2, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 59) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (59, '15.1', N'Профессиональное училище', 4, 4, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 60) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (60, '15.2', N'Профессиональный лицей', 4, 4, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 61) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (61, '15.3', N'Учебный центр', 4, 4, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 62) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (62, '15.4', N'Учебно-производственный центр', 4, 4, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 63) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (63, '15.5', N'Технический лицей', 4, 4, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 64) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (64, '15.6', N'Учебно-курсовой комбинат', 4, 4, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 65) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (65, '16.1', N'Техникум', 4, 4, 16);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 66) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (66, '16.2', N'Колледж', 4, 4, 16);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 67) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (67, '17.1', N'Университет', 6, 6, 17);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 68) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (68, '17.2', N'Академия', 6, 6, 17);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 69) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (69, '17.3', N'Институт', 6, 6, 17);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 70) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (70, '18.1', N'Военный университет', 6, 6, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 71) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (71, '18.2', N'Военная академия', 6, 6, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 72) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (72, '18.3', N'Военный институт', 6, 6, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 73) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (73, '19.1', N'Академия дополнительного профессионального образования', 4, 4, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 74) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (74, '19.2', N'Институт повышения квалификации', 4, 4, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 75) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (75, '19.3', N'Курсы повышения квалификации', 4, 4, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.EO_FORMS WHERE EOFORMID = 76) INSERT INTO dbo.EO_FORMS (EOFORMID, CLASSIFIERCODE, NAME, FUNCTIONALITYTYPEID, REAL_FUNCTIONALITYTYPEID, EOTYPEID) VALUES (76, '19.4', N'Центр повышения квалификации', 4, 4, 19);

-- ROLES <- enum Role
DELETE FROM dbo.ROLES;
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (1, N'Администратор', N'Адм');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (2, N'Завуч', N'Зав');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (3, N'Учитель', N'Уч');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (4, N'Ученик', N'Ученик');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (5, N'Родитель', N'Родит');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (6, N'Младший персонал', N'МлПерс');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (7, N'Секретарь', N'Секр');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (8, N'Медработник', N'Мед');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (9, N'Психолог', N'Псих');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (10, N'Специалист', N'Спец');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (11, N'Администратор ОУО', N'АдмОУО');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (12, N'Руководитель ОУО', N'РукОУО');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (13, N'Специалист ОУО', N'СпецОУО');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (14, N'Оператор ОУО', N'ОперОУО');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (15, N'Координатор ДО', N'КоордДО');
INSERT INTO dbo.ROLES (ROLEID, ROLENAME, SHORTNAME) VALUES (16, N'Координатор мероприятий', N'КоордМер');

-- RIGHTS <- enum Right; DEFAULTROLESRIGHTS: administrator gets everything
DELETE FROM dbo.RIGHTS; DELETE FROM dbo.DEFAULTROLESRIGHTS;
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1, N'arProfileEditSchoolInfo');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (65, N'arProfileViewSchoolInfo');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (2, N'arProfileEditRegionalSettings');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (3, N'arProfileDefineSecurityRoles');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (45, N'arEditReferenceBook');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (58, N'arEditSchoolSettings');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (5, N'arUsersEditStaff');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (66, N'arUsersEditStaffMedInfo');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (6, N'arUsersEditStudents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (67, N'arUsersEditStudentsMedInfo');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (68, N'arUsersEditStudentsPsyInfo');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (73, N'arUsersEditAccountStaff');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (74, N'arUsersEditAccountStudentsParents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (75, N'arUsersEditAccountStudentsParentsInClass');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (29, N'arCreateCloseEditYear');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (37, N'arSchoolSubjects');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (30, N'arCreateEditTerm');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (44, N'arEditSchoolTermTypes');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (50, N'arMoveBookView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (51, N'arMoveBookEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (52, N'arMovePoolStudents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (53, N'arMovePoolStaff');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (61, N'arSchoolDocsView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (62, N'arSchoolDocsEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (36, N'arClassMgmViewClassSubjAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (7, N'arClassMgmCreateClass');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (38, N'arClassMgmEditSubjects');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (8, N'arClassMgmEnrollClass');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (11, N'arClassMgmPostClassEventSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (14, N'arClassMgmPostClassEventAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (40, N'arCurrMgmViewSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (39, N'arCurrMgmViewAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (12, N'arCurrMgmCreate');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (13, N'arCurrMgmCreateAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (60, N'arAddLA');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (15, N'arCalendarViewSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (16, N'arCalendarViewAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (19, N'arCalendarCreateCalendar');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (33, N'arPostSchoolEvent');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (83, N'arViewAwardEvents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (84, N'arPostAwardEvents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (85, N'arEditAwardEventMembers');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (86, N'arViewSelfAwardEvents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (87, N'arSelfRegisterForAwardEvents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (88, N'arEditSelfAwardEventResults');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (20, N'arJournalViewSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (18, N'arJournalViewAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (17, N'arJournalEditSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (23, N'arJournalEditAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (59, N'arJournalEditHAOnlyOnFuture');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (34, N'arTotalsViewSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (31, N'arTotalsViewAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (41, N'arTotalsEditSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (32, N'arTotalsEditAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (9, N'arLASetPolicies');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (10, N'arLACreateGradingScales');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (35, N'arLAViewMaterials');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (4, N'arLAEditSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (42, N'arLAViewSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (43, N'arLAViewAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (21, N'arReportsForAssignedClass');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (22, N'arReportsForAllClasses');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (24, N'arReportsViewForAssignedClass');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (54, N'arReportsViewAdditionalReports');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (55, N'arReportsUseReportConstructor');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (64, N'arReportsViewAdministrativeReports');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (25, N'arAnnouncementView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (26, N'arAnnouncementPost');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (27, N'arMessagesSendReceive');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (56, N'arForumSendReceive');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (57, N'arForumEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (28, N'arAssignmentsViewComplete');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (46, N'arShortInfoStaff');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (47, N'arShortInfoStudents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (48, N'arEditInfoSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (49, N'arEnrollSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (63, N'arDeleteUsers');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (69, N'arEditSchoolResources');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (72, N'arSetPhoto');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (76, N'arBrowseResultsEGEAllClasses');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (77, N'arBrowseResultsEGEHisClassesOrSubjects');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (78, N'arSchoolPublicDocsView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (79, N'arBrowseStatReports');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (80, N'arFillStatReports');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (81, N'arBrowseAccessJournal');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (82, N'arUserStat');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (91, N'arIndividualSupportStudentsReestrView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (92, N'arAddIndividualSupportStudents');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (93, N'arIndividualSupportMeasuresEditAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (94, N'arIndividualSupportMeasuresEditSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (100, N'arReportsViewSpecialEducNeeds');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (101, N'arViewHealthMonitoring');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (102, N'arEditHealthMonitoring');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (104, N'arViewFoodPayOrders');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (105, N'arEditFoodPayOrders');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (106, N'arEditFoodPayStudentOrdersAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (107, N'arEditFoodPayStudentOrdersSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (108, N'arEditFoodPayBalanceAll');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (109, N'arEditFoodPayBalanceSelf');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (110, N'arPostFoodPayStudentOrders');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (111, N'arFoodPayPayment');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (112, N'arEditFoodPayNorms');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1001, N'arEMUsersView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1002, N'arEMUsersEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1003, N'arEMEventsView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1004, N'arEMEventsEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1005, N'arEMReports');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1006, N'arEMPersonDataReports');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1007, N'arEMAddReportsView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1008, N'arEMAddReportsEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1009, N'arEMMovement');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1010, N'arEMStats');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1011, N'arEMEgeView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1012, N'arEMEgeImport');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1013, N'arEMMsoko');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1014, N'arEMDouPayNormView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1015, N'arEMDouPayNormEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1016, N'arEMCuratorsODView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1017, N'arEMCuratorsODEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1018, N'arEMODView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1019, N'arEMODEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1020, N'arEMEventsMembersView');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1021, N'arEMEventsMembersEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1022, N'arrEMPassRateEdit');
INSERT INTO dbo.RIGHTS (RIGHTID, RIGHTNAME) VALUES (1023, N'arEMUserClones');
INSERT INTO dbo.DEFAULTROLESRIGHTS (ROLEID, RIGHTID) SELECT 1, RIGHTID FROM dbo.RIGHTS;

-- TERMTYPES: ids are hard-coded in SchoolYearDAO.GenerateTermsRanges (1 -> 4 terms, 2 -> 3, 3 -> 2, 4 -> whole year)
-- and COMDataAccess (TERMTYPEID = 4 for "year" profiles). TERMNAME = "<n> <TERMTYPENAME>".
DELETE FROM dbo.TERMTYPES WHERE NOT EXISTS (SELECT 1 FROM dbo.TERMS t WHERE t.TERMTYPEID = TERMTYPES.TERMTYPEID);
SET IDENTITY_INSERT dbo.TERMTYPES ON;
INSERT INTO dbo.TERMTYPES (TERMTYPEID, TERMSCOUNT, TERMTYPENAME, ENABLED)
SELECT v.id, v.cnt, v.name, 'Y' FROM (VALUES (1, 4, N'четверть'), (2, 3, N'триместр'), (3, 2, N'полугодие'), (4, 1, N'год')) v(id, cnt, name)
WHERE NOT EXISTS (SELECT 1 FROM dbo.TERMTYPES x WHERE x.TERMTYPEID = v.id);
SET IDENTITY_INSERT dbo.TERMTYPES OFF;

-- PERIODTYPES: kinds of final marks in YEARTOTALS. Code relies on ids 2 (year mark) and 4 (final mark),
-- ISEXAM='Y' for exams; names are reconstructed.
SET IDENTITY_INSERT dbo.PERIODTYPES ON;
INSERT INTO dbo.PERIODTYPES (PERIODTYPEID, NAME, ABBR, TITLE, TYPEORDER, IsExam, GradingSys)
SELECT v.id, v.name, v.abbr, v.title, v.ord, v.ex, 0 FROM (VALUES
    (1, N'Промежуточная', N'Пром', N'Промежуточная оценка', 1, 'N'),
    (2, N'Годовая',       N'Год',  N'Годовая оценка',       2, 'N'),
    (3, N'Экзаменационная', N'Экз', N'Экзаменационная оценка', 3, 'Y'),
    (4, N'Итоговая',      N'Итог', N'Итоговая оценка',      4, 'N')) v(id, name, abbr, title, ord, ex)
WHERE NOT EXISTS (SELECT 1 FROM dbo.PERIODTYPES x WHERE x.PERIODTYPEID = v.id);
SET IDENTITY_INSERT dbo.PERIODTYPES OFF;


-- DEFAULTCOMPONENTS (FGOS curriculum parts); id 1 is the only one copied for pre-schools
DELETE FROM dbo.DEFAULTCOMPONENTS;
INSERT INTO dbo.DEFAULTCOMPONENTS (COMPONENTID, COMPONENTNAME, ORDERNO) VALUES
    (1, N'Обязательная часть', 1),
    (2, N'Часть, формируемая участниками образовательных отношений', 2),
    (3, N'Внеурочная деятельность', 3);


-- Service component 0 ("no component" / total load): legacy SQL inserts COMPONENTID = 0 into CURICULUM* tables
IF NOT EXISTS (SELECT 1 FROM dbo.COMPONENTS WHERE COMPONENTID = 0)
BEGIN
    SET IDENTITY_INSERT dbo.COMPONENTS ON;
    INSERT INTO dbo.COMPONENTS (COMPONENTID, COMPONENTNAME, ORDERNO, ISDELETED, SCHOOLID) VALUES (0, N'Предельно допустимая нагрузка', 0, 1, NULL);
    SET IDENTITY_INSERT dbo.COMPONENTS OFF;
END;


-- DEFAULTEVENTS template (base school year 2000/2001; CopyEventsToNewYear shifts by whole years)
DELETE FROM dbo.DEFAULTEVENTS;
INSERT INTO dbo.DEFAULTEVENTS (NAME, STARTTIME, ENDTIME, ETYPE) VALUES
    (N'Осенние каникулы',          '20001028', '20001105', 3),
    (N'Зимние каникулы',           '20001229', '20010108', 3),
    (N'Весенние каникулы',         '20010324', '20010401', 3),
    (N'Летние каникулы',           '20010601', '20010831', 3),
    (N'День народного единства',   '20001104', '20001104', 4),
    (N'Новогодние праздники',      '20010101', '20010108', 4),
    (N'День защитника Отечества',  '20010223', '20010223', 4),
    (N'Международный женский день','20010308', '20010308', 4),
    (N'Праздник Весны и Труда',    '20010501', '20010501', 4),
    (N'День Победы',               '20010509', '20010509', 4),
    (N'День России',               '20010612', '20010612', 4);

DELETE FROM dbo.CLASSFORMS;
INSERT INTO dbo.CLASSFORMS (CLASSFORMID, CLASSFORMNAME) VALUES (1, N'Очная'), (2, N'Очно-заочная'), (3, N'Заочная');


-- ---------------------------------------------------------------- school info parameters (SchoolInfoParameterField)
DELETE FROM dbo.SCHOOLINFOPARAMS WHERE NOT EXISTS (SELECT 1 FROM dbo.SCHOOLINFO si WHERE si.PARAMID = SCHOOLINFOPARAMS.PARAMID);
-- PARAMID is IDENTITY after 08_insert_defaults.sql (new card params inserted by the app), ids must follow the enum
IF COLUMNPROPERTY(OBJECT_ID('dbo.SCHOOLINFOPARAMS'), 'PARAMID', 'IsIdentity') = 1 SET IDENTITY_INSERT dbo.SCHOOLINFOPARAMS ON;
INSERT INTO dbo.SCHOOLINFOPARAMS (PARAMID, NAME, PageNum, PTYPE, cellOrder)
SELECT v.id, v.name, v.page, v.ptype, v.ord FROM (VALUES
    (1, 'T00address', 1, 'STRING', 1),
    (2, 'T00email', 1, 'STRING', 2),
    (3, 'T00fax', 1, 'STRING', 3),
    (4, 'T00fio1', 1, 'STRING', 4),
    (5, 'T00fio2', 1, 'STRING', 5),
    (6, 'T00fio3', 1, 'STRING', 6),
    (7, 'T00fio4', 1, 'STRING', 7),
    (8, 'T00inn', 1, 'STRING', 8),
    (9, 'T00kpp', 1, 'STRING', 9),
    (10, 'T00name', 1, 'STRING', 10),
    (11, 'T00okato', 1, 'STRING', 11),
    (12, 'T00okfs', 1, 'STRING', 12),
    (13, 'T00okogu', 1, 'STRING', 13),
    (14, 'T00okopf', 1, 'STRING', 14),
    (15, 'T00okpo', 1, 'STRING', 15),
    (16, 'T00okved', 1, 'STRING', 16),
    (17, 'T00phones', 1, 'STRING', 17),
    (18, 'T00spec', 1, 'STRING', 18),
    (19, 'T00Independ', 1, 'STRING', 19),
    (20, 'TnumberLic', 2, 'STRING', 20),
    (21, 'TregNumberLic', 2, 'STRING', 21),
    (22, 'TdateLic', 2, 'STRING', 22),
    (23, 'TdateCloseActionLic', 2, 'STRING', 23),
    (24, 'TnumberLicAES', 2, 'STRING', 24),
    (25, 'TregNumberLicAES', 2, 'STRING', 25),
    (26, 'TdateLicAES', 2, 'STRING', 26),
    (27, 'TdateCloseLicAES', 2, 'STRING', 27),
    (28, 'TnumberAccreditation', 2, 'STRING', 28),
    (29, 'TregNumAccreditation', 2, 'STRING', 29),
    (30, 'TdateAccreditation', 2, 'STRING', 30),
    (31, 'TdateCloseAccred', 2, 'STRING', 31),
    (32, 'T00web', 1, 'STRING', 32),
    (33, 'T00bankScore', 1, 'STRING', 33),
    (34, 'T00corrScore', 1, 'STRING', 34),
    (35, 'T00bik', 1, 'STRING', 35),
    (36, 'T00bankNote', 1, 'STRING', 36),
    (37, 'T00ogrn', 1, 'STRING', 37),
    (38, 'T00addressesAdditionalBuildings', 1, 'STRING', 38),
    (39, 'T00computersCount', 1, 'STRING', 39),
    (40, 'T00contentFilteringName', 1, 'STRING', 40),
    (41, 'T00internetSpeedUnderContract', 1, 'STRING', 41),
    (42, 'T00internetSpeedInFact', 1, 'STRING', 42),
    (43, 'T00internetProviderName', 1, 'STRING', 43),
    (44, 'T00internetAccessTechnology', 1, 'STRING', 44),
    (45, 'TseriaLic', 2, 'STRING', 45),
    (46, 'TseriaLicAES', 2, 'STRING', 46),
    (47, 'TseriaAccreditation', 2, 'STRING', 47),
    (48, 'T00about', 1, 'STRING', 48),
    (50, 'T00bankName', 1, 'STRING', 50),
    (51, 'T00bankKpp', 1, 'STRING', 51),
    (52, 'T00juridicalAddress', 1, 'STRING', 52),
    (53, 'T00additionalName', 1, 'STRING', 53),
    (54, 'T00maxOccupancy', 1, 'STRING', 54),
    (55, 'T00maxOccupancyOnShift', 1, 'STRING', 55),
    (56, 'T00NumberShifts', 1, 'STRING', 56),
    (80, 'T00SmallOrganization', 1, 'BOOL', 80),
    (81, 'T00CollegiateManagement', 1, 'STRING', 81),
    (82, 'T00ReferenceToCharter', 1, 'STRING', 82),
    (83, 'T00PresenceOfPool', 1, 'BOOL', 83),
    (84, 'T00BarrierFreeEnvironment', 1, 'BOOL', 84),
    (85, 'T00VideoSurveillance', 1, 'BOOL', 85),
    (86, 'T00LinkToScanCopyLicenseEducation', 2, 'STRING', 86),
    (87, 'T00LinkToScanCopyLicenseAdd', 2, 'STRING', 87),
    (88, 'T00LinkToScanCopyLicenseAccred', 2, 'STRING', 88),
    (89, 'T00SocialPartnership', 1, 'STRING', 89),
    (90, 'T00EducationProcessStructure', 1, 'STRING', 90),
    (75, 'T00decisionLicenseOrder', 2, 'STRING', 75),
    (58, 'T00decisionLicenseDate', 2, 'STRING', 58),
    (76, 'T00LicenseOrganName', 2, 'STRING', 76),
    (59, 'T00decisionLicenseAESOrder', 2, 'STRING', 59),
    (60, 'T00decisionLicenseAESDate', 2, 'STRING', 60),
    (77, 'T00LicenseAESOrganName', 2, 'STRING', 77),
    (61, 'T00accreditationOrgan', 2, 'STRING', 61),
    (62, 'T00accreditationStatus', 2, 'STRING', 62),
    (63, 'T00accreditationRenewCertificate', 2, 'STRING', 63),
    (78, 'T00decisionAccreditaionOrder', 2, 'STRING', 78),
    (79, 'T00decisionAccreditationDate', 2, 'STRING', 79),
    (64, 'T00accreditationRenewCertificateOrder', 2, 'STRING', 64),
    (66, 'T00accreditationRenewCertificateNumber', 2, 'STRING', 66),
    (65, 'T00accreditationRenewCertificateDate', 2, 'STRING', 65),
    (67, 'T00accreditationSuspensionOrder', 2, 'STRING', 67),
    (68, 'T00accreditationSuspensionDate', 2, 'STRING', 68),
    (69, 'T00accreditationRenewalOrder', 2, 'STRING', 69),
    (70, 'T00accreditationRenewalDate', 2, 'STRING', 70),
    (71, 'T00accreditationDeprivationOrder', 2, 'STRING', 71),
    (72, 'T00accreditationDeprivatoinDate', 2, 'STRING', 72),
    (73, 'T00accreditationStopActionOrder', 2, 'STRING', 73),
    (74, 'T00accreditationStopActionDate', 2, 'STRING', 74),
    (91, 'T00Timetable', 1, 'STRING', 91),
    (92, 'T00ConditionsEducation', 1, 'STRING', 92),
    (100, 'T00FoodPayOrgName', 1, 'STRING', 100),
    (101, 'T00FoodPayInn', 1, 'STRING', 101),
    (102, 'T00FoodPayKpp', 1, 'STRING', 102),
    (103, 'T00FoodPayBankName', 1, 'STRING', 103),
    (104, 'T00FoodPayBankScore', 1, 'STRING', 104),
    (105, 'T00FoodPayBankCorrScore', 1, 'STRING', 105),
    (106, 'T00FoodPayBankBik', 1, 'STRING', 106),
    (107, 'T00FoodPayBankKpp', 1, 'STRING', 107),
    (108, 'T00personalAccount', 1, 'STRING', 108),
    (109, 'T00ProjectForSchool', 1, 'STRING', 109)) v(id, name, page, ptype, ord)
WHERE NOT EXISTS (SELECT 1 FROM dbo.SCHOOLINFOPARAMS p WHERE p.PARAMID = v.id);
IF COLUMNPROPERTY(OBJECT_ID('dbo.SCHOOLINFOPARAMS'), 'PARAMID', 'IsIdentity') = 1 SET IDENTITY_INSERT dbo.SCHOOLINFOPARAMS OFF;


-- ---------------------------------------------------------------- schedule relays (shifts 1..3)
IF COLUMNPROPERTY(OBJECT_ID('dbo.SCHEDULE_RELAYS'), 'RELAY', 'IsIdentity') = 1 SET IDENTITY_INSERT dbo.SCHEDULE_RELAYS ON;
INSERT INTO dbo.SCHEDULE_RELAYS (RELAY) SELECT v.r FROM (VALUES (1), (2), (3)) v(r) WHERE NOT EXISTS (SELECT 1 FROM dbo.SCHEDULE_RELAYS s WHERE s.RELAY = v.r);
IF COLUMNPROPERTY(OBJECT_ID('dbo.SCHEDULE_RELAYS'), 'RELAY', 'IsIdentity') = 1 SET IDENTITY_INSERT dbo.SCHEDULE_RELAYS OFF;


-- ---------------------------------------------------------------- class types (CLASSESTYPES)
IF NOT EXISTS (SELECT 1 FROM dbo.CLASSESTYPES)
BEGIN
    IF COLUMNPROPERTY(OBJECT_ID('dbo.CLASSESTYPES'), 'TYPEID', 'IsIdentity') = 1 SET IDENTITY_INSERT dbo.CLASSESTYPES ON;
    INSERT INTO dbo.CLASSESTYPES (TYPEID, TYPENAME, FUNCTYPEID, SORTORDER, TYPECODE) VALUES
    (1, N'Общеразвивающей направленности', 1, 1, '01'),
    (2, N'Компенсирующей направленности', 1, 2, '02'),
    (3, N'Оздоровительной направленности', 1, 3, '03'),
    (4, N'Комбинированной направленности', 1, 4, '04'),
    (5, N'Общеобразовательный', 2, 1, NULL),
    (6, N'С углублённым изучением отдельных предметов', 2, 2, NULL),
    (7, N'Профильный', 2, 3, NULL),
    (8, N'Гимназический', 2, 4, NULL),
    (9, N'Лицейский', 2, 5, NULL),
    (10, N'Кадетский', 2, 6, NULL),
    (11, N'Специальное коррекционное обучение', 2, 7, NULL),
    (12, N'Общеразвивающий', 3, 1, NULL),
    (13, N'Общий', 4, 1, NULL),
    (14, N'Общий', 5, 1, NULL),
    (15, N'Общий', 6, 1, NULL);
    IF COLUMNPROPERTY(OBJECT_ID('dbo.CLASSESTYPES'), 'TYPEID', 'IsIdentity') = 1 SET IDENTITY_INSERT dbo.CLASSESTYPES OFF;
END;


-- ---------------------------------------------------------------- global school years
-- GLOBALYEARID = year - 2000 (SchoolYearDAO.CreateWizardYear: new DateTime(2000 + gYearID, 9, 1)).
DELETE FROM dbo.GLOBALYEARS WHERE NOT EXISTS (SELECT 1 FROM dbo.SCHOOLYEARS sy WHERE sy.GLOBALYEARID = GLOBALYEARS.GLOBALYEARID);
INSERT INTO dbo.GLOBALYEARS (GLOBALYEARID, SCHOOLYEARNAME, STARTDATE, ENDDATE)
SELECT v.id, v.name, v.s, v.e FROM (VALUES
    (25, '2025/2026', CAST('20250901' AS datetime2), CAST('20260831' AS datetime2)),
    (26, '2026/2027', CAST('20260901' AS datetime2), CAST('20270831' AS datetime2)),
    (27, '2027/2028', CAST('20270901' AS datetime2), CAST('20280831' AS datetime2))) v(id, name, s, e)
WHERE NOT EXISTS (SELECT 1 FROM dbo.GLOBALYEARS g WHERE g.GLOBALYEARID = v.id);

-- ---------------------------------------------------------------- movement periods
-- MOV_PERIODS: the app creates them together with a global year (SchoolYearDAO/CreateSchoolYearService.ProcessMovePeriods,
-- GetDefaultMovePeriods(calendarYear = YEAR(STARTDATE)), STATUS=1). Years seeded above bypass that code, and without
-- rows the move book shows "Движение запрещено администратором сервера" (EditMovePeriods.asp only UPDATEs existing rows).
INSERT INTO dbo.MOV_PERIODS (GLOBALYEARID, PERIODID, STARTDATE, ENDDATE, STATUS)
SELECT g.GLOBALYEARID, p.id,
       DATEFROMPARTS(YEAR(g.STARTDATE) + p.sy, p.sm, p.sd), DATEFROMPARTS(YEAR(g.STARTDATE) + p.ey, p.em, p.ed), 1
FROM dbo.GLOBALYEARS g
CROSS JOIN (VALUES (1, 0, 6, 1, 0, 9, 20), (2, 0, 9, 21, 0, 12, 19), (3, 0, 12, 20, 1, 3, 10), (4, 1, 3, 11, 1, 5, 31)) p(id, sy, sm, sd, ey, em, ed)
WHERE NOT EXISTS (SELECT 1 FROM dbo.MOV_PERIODS m WHERE m.GLOBALYEARID = g.GLOBALYEARID AND m.PERIODID = p.id);

-- ---------------------------------------------------------------- country
-- Regions, districts, cities and schools are created by the server administrator in the UI
-- (/asp/administration/manageArea.asp, createschool.asp). There is no UI for countries.
IF NOT EXISTS (SELECT 1 FROM dbo.COUNTRIES) INSERT INTO dbo.COUNTRIES (COUNTRYNAME) VALUES (N'Россия');

-- ---------------------------------------------------------------- ATO_TYPES (KLADR SOCRBASE abbreviations)
-- LEVELABBR = KLADR level: 1 region, 2 district, 3 city, 4 settlement, 5 street
-- (AddressRefsDao.GetAtoTypes(level), GetAtoTypeIdByNameAndLevel(..., 4)).
INSERT INTO dbo.ATO_TYPES (FULLNAME, SHORTNAME, LEVELABBR)
SELECT v.f, v.s, v.l FROM (VALUES
    (N'Республика', N'Респ', 1), (N'Край', N'край', 1), (N'Область', N'обл', 1), (N'Город федерального значения', N'г', 1),
    (N'Автономная область', N'Аобл', 1), (N'Автономный округ', N'АО', 1),
    (N'Район', N'р-н', 2), (N'Улус', N'у', 2), (N'Городской округ', N'г.о.', 2), (N'Муниципальный округ', N'м.о.', 2), (N'Территория', N'тер', 2),
    (N'Город', N'г', 3), (N'Поселок городского типа', N'пгт', 3), (N'Рабочий поселок', N'рп', 3), (N'Курортный поселок', N'кп', 3),
    (N'Сельсовет', N'с/с', 3), (N'Сельская администрация', N'с/а', 3), (N'Сельское поселение', N'с/п', 3), (N'Наслег', N'наслег', 3),
    (N'Город', N'г', 4), (N'Поселок городского типа', N'пгт', 4), (N'Рабочий поселок', N'рп', 4), (N'Поселок', N'п', 4),
    (N'Село', N'с', 4), (N'Деревня', N'д', 4), (N'Станица', N'ст-ца', 4), (N'Хутор', N'х', 4), (N'Аул', N'аул', 4),
    (N'Слобода', N'сл', 4), (N'Местечко', N'м', 4), (N'Микрорайон', N'мкр', 4), (N'Станция', N'ст', 4), (N'Садовое товарищество', N'снт', 4),
    (N'Улица', N'ул', 5), (N'Проспект', N'пр-кт', 5), (N'Переулок', N'пер', 5), (N'Площадь', N'пл', 5), (N'Бульвар', N'б-р', 5),
    (N'Шоссе', N'ш', 5), (N'Проезд', N'проезд', 5), (N'Набережная', N'наб', 5), (N'Тупик', N'туп', 5), (N'Микрорайон', N'мкр', 5),
    (N'Квартал', N'кв-л', 5), (N'Аллея', N'аллея', 5), (N'Тракт', N'тракт', 5), (N'Линия', N'линия', 5)) v(f, s, l)
WHERE NOT EXISTS (SELECT 1 FROM dbo.ATO_TYPES a WHERE a.SHORTNAME = v.s AND a.LEVELABBR = v.l);

-- ---------------------------------------------------------------- installation region / district / city
-- Every address registry (schools, regions, cities) sets its default filters from the "main city"
-- (CityDao.TryGetMainCityInfo: the city with most schools) and throws NullReferenceException when there
-- is no city at all - so the first city cannot be created in the UI. The installer normally creates
-- the installation region and city; rename them in "Справочники" as needed.
IF NOT EXISTS (SELECT 1 FROM dbo.CITIES)
BEGIN
    DECLARE @inst_country INT = (SELECT TOP 1 COUNTRYID FROM dbo.COUNTRIES ORDER BY COUNTRYID), @inst_state INT, @inst_province INT;
    INSERT INTO dbo.STATES (STATEPROVINCENAME, COUNTRYID) VALUES (N'Регион установки', @inst_country);  SET @inst_state = SCOPE_IDENTITY();
    INSERT INTO dbo.PROVINCES (PROVINCENAME, STATEID) VALUES (N'Район установки', @inst_state);          SET @inst_province = SCOPE_IDENTITY();
    -- SETTLEMENTTYPEID / AVAILABILITYOFSTREET are read as (int) without NULL check (Mappings.CityMapping)
    INSERT INTO dbo.CITIES (NAME, PROVINCEID, STATE_PROVINCEID, SETTLEMENTTYPEID, AVAILABILITYOFSTREET) VALUES (N'Населённый пункт установки', @inst_province, @inst_state, 1, 1);
END;

-- ---------------------------------------------------------------- server administrator
-- ServAdminAuthData always logs in as '_sad_min_'; SecurityDAO.IsStandardPassword() = md5('servadmin'),
-- the system asks to change it on first login. Login page: /asp/administration/salogin.asp (password only).
IF NOT EXISTS (SELECT 1 FROM dbo.USERS WHERE LOGINNAME = '_sad_min_')
    INSERT INTO dbo.USERS (LASTNAME, FIRSTNAME, MIDDLENAME, NOMIDDLENAME, NICKNAME, LOGINNAME, PASSWORD, GENDER, LOGINTYPE, ISDELETED, MODIFYDATE)
    VALUES (N'Администратор', N'сервера', '', 0, N'Администратор сервера', '_sad_min_', '6ee28bd54529e6c64ebd79e3be6c5097', N'М', 0, 0, SYSDATETIME());

COMMIT;

