RewriteFilterPriority HIGH
 
# Versioned css and js links
RewriteRule ^(/js/)(v\d\.\d+\.\d+/|vtrunk\.\d+)(.+.(js|map|coffee))$ /js/$3 [I,L]
RewriteRule ^(/css/)(v\d\.\d+\.\d+/|vtrunk\.\d+)(.+.(less|css))$ /css/$3 [I,L]


# Filedocs clear urls
RewriteRule ^/doc/([^?]+)(/?.*)$ /scripts/ShowDoc.asp$2 [I,L]
RewriteRule ^/schooldoc/([^?]+)(/?.*)$ /asp/SetupSchool/Resources/FileDoc.asp$2 [I,L]
RewriteRule ^/portfolio/([^?]+)(/?.*)$ /asp/SetupSchool/Portfolio/FileDoc.asp$2 [I,L]

# RewriteRule ^/(?!break.html$)(.*)(?<!\.(jpg|css|png|gif))$      /break.html

RewriteRule ^/angular\/([^/?]+)\/([^/?]+)([^?]*)\??(.*) /angular.asp?module=$1&submodule=$2&$4 [I,L]

RewriteRule ^/asp/sso/([^/]*)/callback/([^?]+)\??(.*) /asp/sso/callback/$2.asp?idp=$1&$3 [I,L]

RewriteRule ^/asp/sso/([^/]*)/crosslogin /asp/sso/CrossLogin.asp?idp=$1&$3 [I,L]

#RewriteRule ^(?i)/api/lacc/([^/?]*)\??([^/]*)$ /lacc.asp?Function=$1&$2 [I,L]

RewriteRule ^/about.asp(/?.*)$ /about.html$2 [I,L]

